//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirectAuthorCheckinTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BingMapsV7_0TestFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BingMapsV7_0TestFiles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DirectAuthorCheckinTests.BingMapsV7.0TestFiles", typeof(BingMapsV7_0TestFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (function(){window.Microsoft=window.Microsoft||{};window.Microsoft.Maps=window.Microsoft.Maps||{};var b={domain:&quot;http://ecn.dev.virtualearth.net/mapcontrol/v7.0&quot;,version:&quot;7.0.2011100111334.47&quot;,locale:&quot;en-us&quot;,ishttpsenabled:false,onloadcallback:&quot;__onscriptload__&quot;,tilegeneration:836,zoomOriginWidth:256,defaultTileSize:256,minMercatorZoom:1,maxMercatorZoom:20,maxFPS:60,maxConcurrentTileDownloads:12,spacerImageUrl:&quot;http://www.bing.com/maps/i/spacer.gif&quot;,disableVenueMaps:false,disableDirections:false,disableStre [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mapcontrol {
            get {
                return ResourceManager.GetString("mapcontrol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.Maps.Gimme=function(){var b=function(){var c,b,a,e,j,n;function u(b,a,c){return e[a](b,c)}function s(e,a){var b=[],d=a.length;do{var c=h(e,a[--d]||a);c&amp;&amp;b.push(c)}while(d);return b}function h(c,b){if(c===document||!b)return b;var a=b;while((a=a.parentNode)&amp;&amp;a!==c);return a===c&amp;&amp;b||null}function r(a,b){return h(a,document.getElementById(b))}function i(a,c){c=c||document;if(a.id)return o([r(c,a.id)],a);delete a.id;var b=c.getElementsByTagName(a.tag||&quot;*&quot;);if((!a.classes||a.classes.length&lt;1)&amp;&amp;(!a.attr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string veapicore {
            get {
                return ResourceManager.GetString("veapicore", resourceCulture);
            }
        }
    }
}
