//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirectAuthorCheckinTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Bug271685TestFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Bug271685TestFiles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DirectAuthorCheckinTests.Bug271685TestFiles", typeof(Bug271685TestFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /// &lt;loc filename=&quot;D:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Web.Extensions\v4.0_4.0.0.0__31bf3856ad364e35\System.Web.Extensions.dll&quot; /&gt;
        /////-----------------------------------------------------------------------
        ///// Copyright (C) Microsoft Corporation. All rights reserved.
        /////-----------------------------------------------------------------------
        ///// MicrosoftAjax.js
        ///// Microsoft AJAX Framework.
        /// 
        ///Function.__typeName = &apos;Function&apos;;
        ///Function.__class = true;
        ///Function.createCallback = function Func [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _02_MicrosoftAjax_debug {
            get {
                return ResourceManager.GetString("_02_MicrosoftAjax_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if (intellisense) {
        ///
        ///intellisense.enableMicrosoftAjaxLog = function (logLevel) { 
        ////// &lt;summary&gt;Enables Microsoft Ajax VSIntellisense extension logging&lt;/summary&gt;
        ////// &lt;param name=&quot;logLevel&quot; type=&quot;String&quot;&gt;Acceptable values are &quot;info&quot;, &quot;warning&quot;, and &quot;error&quot;&lt;/param&gt;
        ///
        ///    intellisense.logMessage(&quot;Passed in log level is &quot; + logLevel);
        ///    if(logLevel) {
        ///        switch(logLevel.trim().toLowerCase())
        ///        {
        ///            case &quot;info&quot;:
        ///                intellisense[&quot;MicrosoftAjaxLogLevelInfo&quot;] = true;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _03_AjaxExtensions {
            get {
                return ResourceManager.GetString("_03_AjaxExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /// &lt;loc filename=&quot;D:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Web.Extensions\v4.0_4.0.0.0__31bf3856ad364e35\System.Web.Extensions.dll&quot; /&gt;
        /////-----------------------------------------------------------------------
        ///// Copyright (C) Microsoft Corporation. All rights reserved.
        /////-----------------------------------------------------------------------
        ///// MicrosoftAjaxWebForms.js
        ///// Microsoft AJAX ASP.NET WebForms Framework.
        ///Type._registerScript(&quot;MicrosoftAjaxWebForms.js&quot;, [
        ///	&quot;MicrosoftAjaxCore.js&quot;,
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _04_MicrosoftAjaxWebForms_debug {
            get {
                return ResourceManager.GetString("_04_MicrosoftAjaxWebForms_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Name:        MicrosoftAjax.debug.js
        ///// Assembly:    System.Web.Ajax
        ///// Version:     3.0.31106.22099
        ///// FileVersion: 3.0.31106.0
        ///
        ///
        ///(function(window, Sys) {
        ///
        ///var merge = function _merge(target) {
        ///    target = target || {};
        ///    foreach(arguments, function(o) {
        ///        if (o) {
        ///            forIn(o, function(v, n) {
        ///                target[n] = v;
        ///            });
        ///        }
        ///    }, 1);
        ///    return target;
        ///}
        ///var forIn = function _forIn(obj, callback) {
        ///    for (var x in obj) {
        ///        callback [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _05_MicrosoftAjax_debug {
            get {
                return ResourceManager.GetString("_05_MicrosoftAjax_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Name:        MicrosoftAjaxAdoNet.debug.js
        ///// Assembly:    System.Web.Ajax
        ///// Version:     3.0.31106.22099
        ///// FileVersion: 3.0.31106.0
        ////// &lt;reference name=&quot;MicrosoftAjaxWebServices.js&quot; /&gt;
        ///(function() {
        ///
        ///function execute() {
        ///Type._registerScript(&quot;MicrosoftAjaxAdoNet.js&quot;, [&quot;MicrosoftAjaxWebServices.js&quot;]);
        ///
        ///var merge = Sys._merge;
        ///
        ///Type.registerNamespace(&quot;Sys.Data&quot;);
        ///
        ///if (!Sys.Data.IDataProvider) {
        ///Sys.Data.IDataProvider = function Sys$Data$IDataProvider() {
        ///}
        ///
        ///    function Sys$Data$IDataPr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _06_MicrosoftAjaxAdoNet_debug {
            get {
                return ResourceManager.GetString("_06_MicrosoftAjaxAdoNet_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        /// * This file has been commented to support Visual Studio Intellisense.
        /// * You should not use this file at runtime inside the browser--it is only
        /// * intended to be used only for design-time IntelliSense.  Please use the
        /// * standard jQuery library for all production use.
        /// *
        /// * Comment version: 1.3.2b
        /// */
        ///
        ////*
        /// * jQuery JavaScript Library v1.3.2
        /// * http://jquery.com/
        /// *
        /// * Copyright (c) 2009 John Resig
        /// *
        /// * Permission is hereby granted, free of charge, to any person obtaining
        /// * a copy of th [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _07_jQueryv1_3_2 {
            get {
                return ResourceManager.GetString("_07_jQueryv1_3_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        /// * jQuery UI 1.7.2
        /// *
        /// * Copyright (c) 2009 AUTHORS.txt (http://jqueryui.com/about)
        /// * Dual licensed under the MIT (MIT-LICENSE.txt)
        /// * and GPL (GPL-LICENSE.txt) licenses.
        /// *
        /// * http://docs.jquery.com/UI
        /// */
        ///;jQuery.ui || (function($) {
        ///
        ///var _remove = $.fn.remove,
        ///	isFF2 = $.browser.mozilla &amp;&amp; (parseFloat($.browser.version) &lt; 1.9);
        ///
        /////Helper functions and ui object
        ///$.ui = {
        ///	version: &quot;1.7.2&quot;,
        ///
        ///	// $.ui.plugin is deprecated.  Use the proxy pattern instead.
        ///	plugin: {
        ///		add: function(mo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _08_JQuery_UI_1_7_2 {
            get {
                return ResourceManager.GetString("_08_JQuery_UI_1_7_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        /// * jQuery UI Accordion 1.7.2
        /// *
        /// * Copyright (c) 2009 AUTHORS.txt (http://jqueryui.com/about)
        /// * Dual licensed under the MIT (MIT-LICENSE.txt)
        /// * and GPL (GPL-LICENSE.txt) licenses.
        /// *
        /// * http://docs.jquery.com/UI/Accordion
        /// *
        /// * Depends:
        /// *	ui.core.js
        /// */
        ///(function($) {
        ///
        ///$.widget(&quot;ui.accordion&quot;, {
        ///
        ///	_init: function() {
        ///
        ///		var o = this.options, self = this;
        ///		this.running = 0;
        ///
        ///		// if the user set the alwaysOpen option on init
        ///		// then we need to set the collapsible option
        ///		// i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _09__jQuery_UI_Accordion_1_7_2 {
            get {
                return ResourceManager.GetString("_09__jQuery_UI_Accordion_1_7_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        /// * jQuery UI Draggable 1.7.2
        /// *
        /// * Copyright (c) 2009 AUTHORS.txt (http://jqueryui.com/about)
        /// * Dual licensed under the MIT (MIT-LICENSE.txt)
        /// * and GPL (GPL-LICENSE.txt) licenses.
        /// *
        /// * http://docs.jquery.com/UI/Draggables
        /// *
        /// * Depends:
        /// *	ui.core.js
        /// */
        ///(function($) {
        ///
        ///$.widget(&quot;ui.draggable&quot;, $.extend({}, $.ui.mouse, {
        ///
        ///	_init: function() {
        ///
        ///		if (this.options.helper == &apos;original&apos; &amp;&amp; !(/^(?:r|a|f)/).test(this.element.css(&quot;position&quot;)))
        ///			this.element[0].style.position = &apos;relative&apos; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _10_jQuery_UI_Draggable_1_7_2 {
            get {
                return ResourceManager.GetString("_10_jQuery_UI_Draggable_1_7_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        /// * jQuery UI Resizable 1.7.2
        /// *
        /// * Copyright (c) 2009 AUTHORS.txt (http://jqueryui.com/about)
        /// * Dual licensed under the MIT (MIT-LICENSE.txt)
        /// * and GPL (GPL-LICENSE.txt) licenses.
        /// *
        /// * http://docs.jquery.com/UI/Resizables
        /// *
        /// * Depends:
        /// *	ui.core.js
        /// */
        ///(function($) {
        ///
        ///$.widget(&quot;ui.resizable&quot;, $.extend({}, $.ui.mouse, {
        ///
        ///	_init: function() {
        ///
        ///		var self = this, o = this.options;
        ///		this.element.addClass(&quot;ui-resizable&quot;);
        ///
        ///		$.extend(this, {
        ///			_aspectRatio: !!(o.aspectRatio),
        ///			 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _11_ui_resizeable {
            get {
                return ResourceManager.GetString("_11_ui_resizeable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        /// * jQuery UI Dialog 1.7.2
        /// *
        /// * Copyright (c) 2009 AUTHORS.txt (http://jqueryui.com/about)
        /// * Dual licensed under the MIT (MIT-LICENSE.txt)
        /// * and GPL (GPL-LICENSE.txt) licenses.
        /// *
        /// * http://docs.jquery.com/UI/Dialog
        /// *
        /// * Depends:
        /// *	ui.core.js
        /// *	ui.draggable.js
        /// *	ui.resizable.js
        /// */
        ///(function($) {
        ///
        ///var setDataSwitch = {
        ///		dragStart: &quot;start.draggable&quot;,
        ///		drag: &quot;drag.draggable&quot;,
        ///		dragStop: &quot;stop.draggable&quot;,
        ///		maxHeight: &quot;maxHeight.resizable&quot;,
        ///		minHeight: &quot;minHeight.resizable&quot;,
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _12_ui_dialog {
            get {
                return ResourceManager.GetString("_12_ui_dialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*! Copyright (c) 2010 Brandon Aaron (http://brandonaaron.net)
        /// * Licensed under the MIT License (LICENSE.txt).
        /// *
        /// * Version 2.1.2
        /// */
        ///
        ///(function($){
        ///
        ///$.fn.bgiframe = ($.browser.msie &amp;&amp; /msie 6\.0/i.test(navigator.userAgent) ? function(s) {
        ///    s = $.extend({
        ///        top     : &apos;auto&apos;, // auto == .currentStyle.borderTopWidth
        ///        left    : &apos;auto&apos;, // auto == .currentStyle.borderLeftWidth
        ///        width   : &apos;auto&apos;, // auto == offsetWidth
        ///        height  : &apos;auto&apos;, // auto == offsetHeight
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _13_jquery_bigframe {
            get {
                return ResourceManager.GetString("_13_jquery_bigframe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        /// * Treeview 1.4 - jQuery plugin to hide and show branches of a tree
        /// * 
        /// * http://bassistance.de/jquery-plugins/jquery-plugin-treeview/
        /// * http://docs.jquery.com/Plugins/Treeview
        /// *
        /// * Copyright (c) 2007 Jörn Zaefferer
        /// *
        /// * Dual licensed under the MIT and GPL licenses:
        /// *   http://www.opensource.org/licenses/mit-license.php
        /// *   http://www.gnu.org/licenses/gpl.html
        /// *
        /// * Revision: $Id: jquery.treeview.js 4684 2008-02-07 19:08:06Z joern.zaefferer $
        /// *
        /// */
        ///
        ///;(function($) {
        ///
        ///	$.extend($.f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _14_Jquery_treeview {
            get {
                return ResourceManager.GetString("_14_Jquery_treeview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        ///* Async Treeview 0.1 - Lazy-loading extension for Treeview
        ///* 
        ///* http://bassistance.de/jquery-plugins/jquery-plugin-treeview/
        ///*
        ///* Copyright (c) 2007 Jörn Zaefferer
        ///*
        ///* Dual licensed under the MIT and GPL licenses:
        ///*   http://www.opensource.org/licenses/mit-license.php
        ///*   http://www.gnu.org/licenses/gpl.html
        ///*
        ///* Revision: $Id$
        ///*
        ///* 12/26/2009 Version 0.1a  Override for different trees in app
        ///*
        ///*
        ///*/
        ///
        ///; (function($) {
        ///
        ///   function load(settings, parentId, cityId, child, container) {
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _15_Jquery_treeview_asyncway {
            get {
                return ResourceManager.GetString("_15_Jquery_treeview_asyncway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        /// =====================================================================
        /// Redistribution and use in source and binary forms, with or without
        /// modification, are permitted provided that the following conditions
        /// are met:
        ///
        /// 1. Redistributions of source code must retain the above
        /// copyright notice, this list of conditions and the following
        /// disclaimer.
        ///
        /// 2. Redistributions in binary form must reproduce the above
        /// copyright notice, this list of conditions and the following
        /// disclaimer in the documen [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _16_vanadium {
            get {
                return ResourceManager.GetString("_16_vanadium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /**
        /// * Cookie plugin
        /// *
        /// * Copyright (c) 2006 Klaus Hartl (stilbuero.de)
        /// * Dual licensed under the MIT and GPL licenses:
        /// * http://www.opensource.org/licenses/mit-license.php
        /// * http://www.gnu.org/licenses/gpl.html
        /// *
        /// */
        ///
        ////**
        /// * Create a cookie with the given name and value and other optional parameters.
        /// *
        /// * @example $.cookie(&apos;the_cookie&apos;, &apos;the_value&apos;);
        /// * @desc Set the value of a cookie.
        /// * @example $.cookie(&apos;the_cookie&apos;, &apos;the_value&apos;, { expires: 7, path: &apos;/&apos;, domain: &apos;jquery.com&apos;, secure [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _17_jquery_cookie {
            get {
                return ResourceManager.GetString("_17_jquery_cookie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///function BrowserType() {
        ///   var srchText = navigator.userAgent;
        ///   var brwTypes = (&quot;Opera,MSIE,Netscape,Firefox,Chrome,Safari&quot;).split(&apos;,&apos;);
        ///   for (var ix = 0; ix &lt; brwTypes.length; ix++) {
        ///      if (srchText.toString().match(brwTypes[ix])) {
        ///         return brwTypes[ix];
        ///      }
        ///   }
        ///   return null;
        ///}
        ///
        ///var pK = 0;
        /////var brwType = BrowserType();
        ///
        ///function EscapeSingleQuote(source) {
        ///   return source.replace(&quot;&apos;&quot;, &quot;\&apos;&quot;);
        ///}
        ///function EscapeDoubleQuoteAndUrl(source) {
        ///   source = source.repla [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _18_utils {
            get {
                return ResourceManager.GetString("_18_utils", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var L_invalidinvoketarget_text=&quot;Invalid invoke target specified.&quot;,L_invaliddirections_text=&quot;Invalid argument passed; both start and end must be present.&quot;,L_invalidpageindex_text=&quot;Invalid search results page index is passed.&quot;,L_invalidelement_text=&quot;Invalid element id; unable to find the element in the document body.&quot;,L_noheadelement_text=&quot;Head element is missing for the current document; cannot initialize the API framework.&quot;,L_noserviceurl_text=&quot;Either a service url or script url is required to create VENetw [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _19_mapcontrol {
            get {
                return ResourceManager.GetString("_19_mapcontrol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///(function(window){
        ///    
        ///    // ----- GENERATED ELEMENTS FROM REFERENCED HTML DOCUMENTS ------
        ///
        ///    window.document._$documentElements = {
        ///        &quot;Head1&quot; : window.document.createElement(&quot;head&quot;),
        ///        &quot;Form1&quot; : window.document.createElement(&quot;form&quot;),
        ///        &quot;WebAuthControl&quot; : window.document.createElement(&quot;iframe&quot;),
        ///        &quot;accordion&quot; : window.document.createElement(&quot;div&quot;),
        ///        &quot;CurrentLiveUser&quot; : window.document.createElement(&quot;span&quot;),
        ///        &quot;navigation&quot; : window.document.createElement( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _20_GeneratedElements {
            get {
                return ResourceManager.GetString("_20_GeneratedElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///   $(function() {
        ///      $(&quot;#accordion&quot;).accordion({
        /////         event: &quot;mouseover&quot;,
        ///			autoHeight: &quot;false&quot;,
        ///			height:&quot;600&quot;
        ///      });
        ///   });
        ///   .
        /// </summary>
        internal static string _24 {
            get {
                return ResourceManager.GetString("_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ////* BEGIN EXTERNAL SOURCE */
        ///
        ///            
        ///       $.ui.dialog.defaults.bgiframe = true;
        ///       $(function () {
        ///           $(&quot;#routeDivId&quot;).dialog({
        ///               autoOpen: false,
        ///               position: &quot;right&quot;
        ///           });
        ///
        ///           $(&quot;#PublishDivId&quot;).dialog({
        ///               autoOpen: false,
        ///               width: 650
        ///           });
        ///
        ///
        ///           $(&quot;#ChooseCityDivId&quot;).dialog({
        ///               autoOpen: false
        ///           });
        ///
        ///           $(&quot;#SearchResultId&quot;).dialog({
        ///               au [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string primaryFile {
            get {
                return ResourceManager.GetString("primaryFile", resourceCulture);
            }
        }
    }
}
