//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirectAuthorCheckinTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class JQueryTestFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JQueryTestFiles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DirectAuthorCheckinTests.JQueryTestFiles", typeof(JQueryTestFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ////*
        ///* This file has been commented to support Visual Studio Intellisense.
        ///* You should not use this file at runtime inside the browser--it is only
        ///* intended to be used only for design-time IntelliSense.  Please use the
        ///* standard jQuery library for all production use.
        ///*
        ///* Comment version: 1.2.6a
        ///*/
        ///
        ///(function () {
        ///    /*
        ///    * jQuery 1.2.6 - New Wave Javascript
        ///    *
        ///    * Copyright (c) 2008 John Resig, http://jquery.com/
        ///    *
        ///    * Permission is hereby granted, free of charge, to any pers [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_1_2_6_vsdoc {
            get {
                return ResourceManager.GetString("jquery_1_2_6_vsdoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        /// * This file has been commented to support Visual Studio Intellisense.
        /// * You should not use this file at runtime inside the browser--it is only
        /// * intended to be used only for design-time IntelliSense.  Please use the
        /// * standard jQuery library for all production use.
        /// *
        /// * Comment version: 1.2.6a
        /// */
        ///
        /// var t01 = (case / 3);                         // ERRsyntax
        ///
        ///(function(){
        ////*
        /// * jQuery 1.2.6 - New Wave Javascript
        /// *
        /// * Copyright (c) 2008 John Resig, http://jquery.com/
        /// *
        /// * Permission [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_1_2_6_vsdoc_error {
            get {
                return ResourceManager.GetString("jquery_1_2_6_vsdoc_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        /// * This file has been commented to support Visual Studio Intellisense.
        /// * You should not use this file at runtime inside the browser--it is only
        /// * intended to be used only for design-time IntelliSense.  Please use the
        /// * standard jQuery library for all production use.
        /// *
        /// * Comment version: 1.4.1a
        /// */
        ///
        ////*!
        /// * jQuery JavaScript Library v1.4.1
        /// * http://jquery.com/
        /// *
        /// * Distributed in whole under the terms of the MIT
        /// *
        /// * Copyright 2010, John Resig
        /// *
        /// * Permission is hereby granted, fr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_1_4_1_vsdoc {
            get {
                return ResourceManager.GetString("jquery_1_4_1_vsdoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * jQuery JavaScript Library v1.4.3
        /// * http://jquery.com/
        /// *
        /// * Copyright 2010, John Resig
        /// * Dual licensed under the MIT or GPL Version 2 licenses.
        /// * http://jquery.org/license
        /// *
        /// * Includes Sizzle.js
        /// * http://sizzlejs.com/
        /// * Copyright 2010, The Dojo Foundation
        /// * Released under the MIT, BSD, and GPL Licenses.
        /// *
        /// * Date: Thu Oct 14 23:10:06 2010 -0400
        /// */
        ///(function( window, undefined ) {
        ///
        ///// Use the correct document accordingly with window argument (sandbox)
        ///var document = window. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_1_4_3 {
            get {
                return ResourceManager.GetString("jquery_1_4_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * jQuery JavaScript Library v1.5.1
        /// * http://jquery.com/
        /// *
        /// * Copyright 2011, John Resig
        /// * Dual licensed under the MIT or GPL Version 2 licenses.
        /// * http://jquery.org/license
        /// *
        /// * Includes Sizzle.js
        /// * http://sizzlejs.com/
        /// * Copyright 2011, The Dojo Foundation
        /// * Released under the MIT, BSD, and GPL Licenses.
        /// *
        /// * Date: Wed Feb 23 13:55:29 2011 -0500
        /// */
        ///(function( window, undefined ) {
        ///
        ///// Use the correct document accordingly with window argument (sandbox)
        ///var document = window. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_1_5_1 {
            get {
                return ResourceManager.GetString("jquery_1_5_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * jQuery JavaScript Library v1.5.2
        /// * http://jquery.com/
        /// *
        /// * Copyright 2011, John Resig
        /// * Dual licensed under the MIT or GPL Version 2 licenses.
        /// * http://jquery.org/license
        /// *
        /// * Includes Sizzle.js
        /// * http://sizzlejs.com/
        /// * Copyright 2011, The Dojo Foundation
        /// * Released under the MIT, BSD, and GPL Licenses.
        /// *
        /// * Date: Thu Mar 31 15:28:23 2011 -0400
        /// */
        ///(function( window, undefined ) {
        ///
        ///// Use the correct document accordingly with window argument (sandbox)
        ///var document = window. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_1_5_2 {
            get {
                return ResourceManager.GetString("jquery_1_5_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * jQuery JavaScript Library v1.6
        /// * http://jquery.com/
        /// * Copyright 2011, John Resig
        /// *
        /// * Includes Sizzle.js
        /// * http://sizzlejs.com/
        /// * Copyright 2011, The Dojo Foundation
        /// *
        /// * Permission is hereby granted, free of charge, to any person obtaining
        /// * a copy of this software and associated documentation files (the
        /// * &quot;Software&quot;), to deal in the Software without restriction, including
        /// * without limitation the rights to use, copy, modify, merge, publish,
        /// * distribute, sublicense, and/or se [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_1_6_1 {
            get {
                return ResourceManager.GetString("jquery_1_6_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        ///* This file has been generated to support Visual Studio IntelliSense.
        ///* You should not use this file at runtime inside the browser--it is only
        ///* intended to be used only for design-time IntelliSense.  Please use the
        ///* standard jQuery library for all production use.
        ///*
        ///* Comment version: 1.6.1
        ///*/
        ///
        ////*!
        ///* jQuery JavaScript Library v1.6.1
        ///* http://jquery.com/
        ///*
        ///* Distributed in whole under the terms of the MIT
        ///*
        ///* Copyright 2010, John Resig
        ///*
        ///* Permission is hereby granted, free of charge, to [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_1_6_1_vsdoc {
            get {
                return ResourceManager.GetString("jquery_1_6_1_vsdoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        ///* jQuery JavaScript Library v1.6.2
        ///* http://jquery.com/
        ///*
        ///* Copyright 2011, John Resig
        ///* Dual licensed under the MIT or GPL Version 2 licenses.
        ///* http://jquery.org/license
        ///*
        ///* Includes Sizzle.js
        ///* http://sizzlejs.com/
        ///* Copyright 2011, The Dojo Foundation
        ///* Released under the MIT, BSD, and GPL Licenses.
        ///*
        ///* Date: Thu Jun 30 14:16:56 2011 -0400
        ///*/
        ///(function (window, undefined) {
        ///
        ///    // Use the correct document accordingly with window argument (sandbox)
        ///    var document = window.documen [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_1_6_2 {
            get {
                return ResourceManager.GetString("jquery_1_6_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * jQuery JavaScript Library v1.6.2
        /// * http://jquery.com/
        /// *
        /// * Copyright 2011, John Resig
        /// * Dual licensed under the MIT or GPL Version 2 licenses.
        /// * http://jquery.org/license
        /// *
        /// * Includes Sizzle.js
        /// * http://sizzlejs.com/
        /// * Copyright 2011, The Dojo Foundation
        /// * Released under the MIT, BSD, and GPL Licenses.
        /// *
        /// * Date: Thu Jun 30 14:16:56 2011 -0400
        /// */
        ///(function(a,b){function cv(a){return f.isWindow(a)?a:a.nodeType===9?a.defaultView||a.parentWindow:!1}function cs(a){if(!cg[a]){var [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_1_6_2_min {
            get {
                return ResourceManager.GetString("jquery_1_6_2_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * jQuery JavaScript Library v1.7
        /// * http://jquery.com/
        /// *
        /// * Copyright 2011, John Resig
        /// * Dual licensed under the MIT or GPL Version 2 licenses.
        /// * http://jquery.org/license
        /// *
        /// * Includes Sizzle.js
        /// * http://sizzlejs.com/
        /// * Copyright 2011, The Dojo Foundation
        /// * Released under the MIT, BSD, and GPL Licenses.
        /// *
        /// * Date: Thu Nov 3 16:18:21 2011 -0400
        /// */
        ///(function( window, undefined ) {
        ///
        ///// Use the correct document accordingly with window argument (sandbox)
        ///var document = window.doc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_1_7 {
            get {
                return ResourceManager.GetString("jquery_1_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * jQuery JavaScript Library v1.7.2
        /// * http://jquery.com/
        /// *
        /// * Copyright 2011, John Resig
        /// * Dual licensed under the MIT or GPL Version 2 licenses.
        /// * http://jquery.org/license
        /// *
        /// * Includes Sizzle.js
        /// * http://sizzlejs.com/
        /// * Copyright 2011, The Dojo Foundation
        /// * Released under the MIT, BSD, and GPL Licenses.
        /// *
        /// * Date: Wed Mar 21 12:46:34 2012 -0700
        /// */
        ///(function( window, undefined ) {
        ///
        ///// Use the correct document accordingly with window argument (sandbox)
        ///var document = window. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_1_7_2 {
            get {
                return ResourceManager.GetString("jquery_1_7_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*! jQuery v1.7 jquery.com | jquery.org/license */
        ///(function(a,b){function cA(a){return f.isWindow(a)?a:a.nodeType===9?a.defaultView||a.parentWindow:!1}function cx(a){if(!cm[a]){var b=c.body,d=f(&quot;&lt;&quot;+a+&quot;&gt;&quot;).appendTo(b),e=d.css(&quot;display&quot;);d.remove();if(e===&quot;none&quot;||e===&quot;&quot;){cn||(cn=c.createElement(&quot;iframe&quot;),cn.frameBorder=cn.width=cn.height=0),b.appendChild(cn);if(!co||!cn.createElement)co=(cn.contentWindow||cn.contentDocument).document,co.write((c.compatMode===&quot;CSS1Compat&quot;?&quot;&lt;!doctype html&gt;&quot;:&quot;&quot;)+&quot;&lt;html&gt;&lt;body&gt;&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_1_7_min {
            get {
                return ResourceManager.GetString("jquery_1_7_min", resourceCulture);
            }
        }
    }
}
