//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirectAuthorCheckinTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SOETestFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SOETestFiles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DirectAuthorCheckinTests.SOETestFiles", typeof(SOETestFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function ActiveXObject(className, location) {
        ///    /// &lt;signature&gt;
        ///    ///   &lt;param name=&quot;className&quot; type=&quot;String&quot; /&gt;
        ///    ///   &lt;param name=&quot;location&quot; type=&quot;String&quot; /&gt;
        ///    /// &lt;/signature&gt;
        ///}
        ///
        ///function VBArray(safeArray) {
        ///    /// &lt;signature&gt;
        ///    ///   &lt;param name=&quot;safeArray&quot; type&quot;VBArray&quot; /&gt;
        ///    /// &lt;/signature&gt;
        ///}
        ///VBArray.prototype.getItem = function () {
        ///    /// &lt;signature&gt;
        ///    ///   &lt;param name=&quot;dimension1&quot; type=&quot;Number&quot; /&gt;
        ///    ///   &lt;param name=&quot;[dimension2]&quot; type=&quot;Number&quot; /&gt;
        ///    ///   &lt;pa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _0_SiteTypes {
            get {
                return ResourceManager.GetString("_0_SiteTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///function _$InitializeAsyncRequests() {
        ///		_$asyncRequests = [{ src: &apos;&apos; }];
        ///}
        ///
        ///var document = { };
        ///(function () {
        ///	function _getEventObject(type, attach) {
        ///		if(attach) return MSEventObj;
        ///		switch(type) {
        ///			case &apos;activate&apos;:
        ///			case &apos;afterprint&apos;:
        ///			case &apos;afterupdate&apos;:
        ///			case &apos;beforeactivate&apos;:
        ///			case &apos;beforecopy&apos;:
        ///			case &apos;beforecut&apos;:
        ///			case &apos;beforedeactivate&apos;:
        ///			case &apos;beforeeditfocus&apos;:
        ///			case &apos;beforepaste&apos;:
        ///			case &apos;beforeprint&apos;:
        ///			case &apos;beforeupdate&apos;:
        ///			case &apos;bounce&apos;:
        ///			case &apos; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _1_OldDom {
            get {
                return ResourceManager.GetString("_1_OldDom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /// &lt;reference path=&apos;base.js&apos; /&gt;
        /// 
        ///
        ///////////////////////////////////////////////////////////////
        ///////   © Microsoft. All rights reserved.                ////
        ///////                                                    ////
        ///////   This library is intended for use in WWAs only.   ////
        ///////////////////////////////////////////////////////////////
        ///// x86fre.fbl_pac_dev 
        /// 
        ///
        ///
        ///
        ///(function (global, undefined) {
        ///
        ///    var expandProperties = function (properties, isStatic) {
        ///        var expandedProperties =  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2 {
            get {
                return ResourceManager.GetString("_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /// &lt;reference path=&apos;base.js&apos; /&gt;
        ////// &lt;reference path=&apos;wwaapp.js&apos; /&gt;
        ////// &lt;reference winrt=&apos;true&apos;  /&gt;
        ////// &lt;reference winrt=&apos;true&apos;  /&gt;
        /// 
        ///
        ///////////////////////////////////////////////////////////////
        ///////   © Microsoft. All rights reserved.                ////
        ///////                                                    ////
        ///////   This library is intended for use in WWAs only.   ////
        ///////////////////////////////////////////////////////////////
        ///// x86fre.fbl_pac_dev 
        /// 
        ///
        ///
        ///
        ///(function (global, Win, unde [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _3 {
            get {
                return ResourceManager.GetString("_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * jQuery JavaScript Library v1.4.2
        /// * http://jquery.com/
        /// *
        /// * Copyright 2010, John Resig
        /// * Dual licensed under the MIT or GPL Version 2 licenses.
        /// * http://jquery.org/license
        /// *
        /// * Includes Sizzle.js
        /// * http://sizzlejs.com/
        /// * Copyright 2010, The Dojo Foundation
        /// * Released under the MIT, BSD, and GPL Licenses.
        /// *
        /// * Date: Sat Feb 13 22:33:48 2010 -0500
        /// */
        ///(function (A, w) { function ma() { if (!c.isReady) { try { s.documentElement.doScroll(&quot;left&quot;) } catch (a) { setTimeout(ma, 1);retu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _4_JQuery {
            get {
                return ResourceManager.GetString("_4_JQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * jQuery JavaScript Library v1.4.2
        /// * http://jquery.com/
        /// *
        /// * Copyright 2010, John Resig
        /// * Dual licensed under the MIT or GPL Version 2 licenses.
        /// * http://jquery.org/license
        /// *
        /// * Includes Sizzle.js
        /// * http://sizzlejs.com/
        /// * Copyright 2010, The Dojo Foundation
        /// * Released under the MIT, BSD, and GPL Licenses.
        /// *
        /// * Date: Sat Feb 13 22:33:48 2010 -0500
        /// */
        ///(function (A, w) {
        ///    function ma() {
        ///        if (!c.isReady) {
        ///            try {
        ///                s.documentElement.doScroll( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _4_JQuery_debug {
            get {
                return ResourceManager.GetString("_4_JQuery_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var jobs = [{ &quot;id&quot;: &quot;741&quot;, &quot;type_id&quot;: &quot;3&quot;, &quot;category_id&quot;: &quot;1&quot;, &quot;category_name&quot;: &quot;Developers&quot;, &quot;company&quot;: &quot;Schematic&quot;, &quot;url&quot;: &quot;http:\/\/www.schematic.com&quot;, &quot;title&quot;: &quot;Freelance Sr. Front End Developer&quot;, &quot;url_title&quot;: &quot;freelance-sr-front-end-developer-at-schematic&quot;, &quot;location&quot;: &quot;Los Angeles, CA 90016&quot;, &quot;description&quot;: &quot;Currently, Schematic has a dynamic Freelance Senior Front- End Developer opportunity to be located in our LA office.  This position involves two primary tasks: Front-end Development and Project Sc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _5 {
            get {
                return ResourceManager.GetString("_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (function () { var k = void 0, aa = encodeURIComponent, l = String, o = Math, ba = &quot;push&quot;, ca = &quot;cookie&quot;, p = &quot;charAt&quot;, q = &quot;indexOf&quot;, da = &quot;getTime&quot;, r = &quot;toString&quot;, t = &quot;window&quot;, v = &quot;length&quot;, w = &quot;document&quot;, x = &quot;split&quot;, y = &quot;location&quot;, ea = &quot;protocol&quot;, fa = &quot;href&quot;, z = &quot;substring&quot;, A = &quot;join&quot;, C = &quot;toLowerCase&quot;;
        ///    var ga = &quot;_gat&quot;, ha = &quot;_gaq&quot;, ia = &quot;4.9.4&quot;, ja = &quot;_gaUserPrefs&quot;, ka = &quot;ioo&quot;, D = &quot;&amp;&quot;, E = &quot;=&quot;, F = &quot;__utma=&quot;, H = &quot;__utmb=&quot;, la = &quot;__utmc=&quot;, ma = &quot;__utmk=&quot;, I = &quot;__utmv=&quot;, J = &quot;__utmz=&quot;, na [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _6 {
            get {
                return ResourceManager.GetString("_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //jQuery Plugin: Drop Shadow Text
        ///// call like this: $(element).textDropShadow();
        ///(function ($) {
        ///    $.fn.textDropShadow = function () {
        ///        $(this).html(&apos;&lt;span class=&quot;jq-shadow&quot;&gt;&apos; + $(this).html() + &apos;&lt;/span&gt;&lt;span&gt;&apos; + $(this).html() + &apos;&lt;/span&gt;&apos;);
        ///        return $(this);
        ///    }
        ///})(jQuery);
        ///
        ///
        ///
        ///// javascript method: &quot;pxToEm&quot;
        ///eval(function (p, a, c, k, e, r) { e = function (c) { return c.toString(a) };if (!&apos;&apos;.replace(/^/, String)) { while (c--)r[e(c)] = k[c] || e(c);k = [function (e) { return r[ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _7_DropShadowText {
            get {
                return ResourceManager.GetString("_7_DropShadowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return X(this, a, b, true, c.attr);
        ///function X(a, b, d, f, e, j) { 
        ///    var i = a.length;
        ///    if (typeof b === &quot;object&quot;) { 
        ///        for (var o in b)
        ///                X(a, o, b[o], f, e, d);
        ///        return a 
        ///    }
        ///        if (d !== w) { 
        ///            f = !j &amp;&amp; f &amp;&amp; c.isFunction(d);
        ///                    for (o = 0; o &lt; i; o++)
        ///            e(a[o], b, f ? d.call(a[o], o, e(a[o], b)) : d, j);
        ///            return a;
        ///        }
        ///            return i ? e(a[0], b) : w;
        ///            }.
        /// </summary>
        internal static string _8 {
            get {
                return ResourceManager.GetString("_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /// &lt;reference path=&apos;../default.html&apos;/&gt;
        ///
        ///
        ///// custom.js
        ///(function($) {
        ///    $.fn.textDropShaow = function() {
        ///        $(this).html(&apos;&lt;span class=&quot;jq-shadow&quot;&gt;&apos; + $(this).html() + &apos;&lt;/span&gt;&lt;span&gt;&apos; + $(this).html() + &apos;&lt;/span&gt;&apos;);
        ///        return $(this);
        ///        }
        ///})(jQuery);
        ///
        ///
        ///jQuery.fn.fixHover = function () {
        ///    $(this).each(function () {
        ///        var hoverClasses = &apos;hover&apos;;
        ///        if ($(this).attr(&apos;class&apos;)) {
        ///            var classes = $(this).attr(&apos;class&apos;);
        ///            var classArray = classes. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string primary {
            get {
                return ResourceManager.GetString("primary", resourceCulture);
            }
        }
    }
}
