//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirectAuthorCheckinTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestFiles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DirectAuthorCheckinTests.TestFiles", typeof(TestFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /// &lt;reference path=&apos;base.js&apos; /&gt;
        /// 
        ///
        ///////////////////////////////////////////////////////////////
        ///////   © Microsoft. All rights reserved.                ////
        ///////                                                    ////
        ///////   This library is intended for use in WWAs only.   ////
        ///////////////////////////////////////////////////////////////
        ///// x86fre.fbl_pac_dev 
        /// 
        ///
        ///
        ///
        ///(function (global, undefined) {
        ///
        ///    var expandProperties = function (properties, isStatic) {
        ///        var expandedProperties =  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _210333_base {
            get {
                return ResourceManager.GetString("_210333_base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (function(window){
        ///    
        ///    // ----- GENERATED ELEMENTS FROM REFERENCED HTML DOCUMENTS ------
        ///
        ///    window.document._$documentElements = {
        ///        &quot;wrapper&quot; : window.document.createElement(&quot;DIV&quot;),
        ///        &quot;header&quot; : window.document.createElement(&quot;DIV&quot;),
        ///        &quot;nav&quot; : window.document.createElement(&quot;DIV&quot;),
        ///        &quot;navPublic&quot; : window.document.createElement(&quot;SPAN&quot;),
        ///        &quot;navPersonal&quot; : window.document.createElement(&quot;SPAN&quot;),
        ///        &quot;content&quot; : window.document.createElement(&quot;DIV&quot;),
        ///        &quot;pub [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _210333_context {
            get {
                return ResourceManager.GetString("_210333_context", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /// &lt;reference path=&quot;../default.html&quot; /&gt;
        ///
        ///var publicFeedUrl = &quot;http://officetalk/api/feeds/public.json&quot;;
        ///var personalFeedUrl = &quot;http://officetalk/api/feeds/personal.json&quot;;
        ///var menuPublicFeed = null;
        ///var menuPersonalFeed = null;
        ///var lastRefresh = null;
        ///
        ///
        /////Debug.enableFirstChanceException(true);
        ///
        ///var app = Win.Application;
        ///
        ///
        ///
        ///app.addEventListener(&quot;loaded&quot;, function() {
        ///
        ///    // hook up click handlers:
        ///    var reload = document.getElementById(&quot;reload&quot;);
        ///    reload.addEventListener(&quot;click&quot;, r [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _210333_default {
            get {
                return ResourceManager.GetString("_210333_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (function () {
        ///var rootNamespace=this,dp=null,dpg=null,shadowableMembers=[&apos;apply&apos;,&apos;call&apos;,&apos;hasOwnProperty&apos;,&apos;isPrototypeOf&apos;,&apos;propertyIsEnumerable&apos;,&apos;toLocalString&apos;,&apos;toString&apos;,&apos;valueOf&apos;];shadowableMembers.contains=function(b){for(var a=0;a&lt;shadowableMembers.length;a++)if(shadowableMembers[a]==b)return true;return false};if(Object.defineProperty==undefined){dp=function(b,a,c){b[a]!=undefined&amp;&amp;!shadowableMembers.contains(a)&amp;&amp;WScript.Echo(&apos;Attempted redefinition of property &apos;+a);b[a]=c};dpg=function(b,a){b[a]!=un [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _210333_winrt {
            get {
                return ResourceManager.GetString("_210333_winrt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /// &lt;reference path=&apos;base.js&apos; /&gt;
        ////// &lt;reference path=&apos;wwaapp.js&apos; /&gt;
        ////// &lt;reference winrt=&apos;true&apos;  /&gt;
        ////// &lt;reference winrt=&apos;true&apos;  /&gt;
        /// 
        ///
        ///////////////////////////////////////////////////////////////
        ///////   © Microsoft. All rights reserved.                ////
        ///////                                                    ////
        ///////   This library is intended for use in WWAs only.   ////
        ///////////////////////////////////////////////////////////////
        ///// x86fre.fbl_pac_dev 
        /// 
        ///
        ///
        ///
        ///(function (global, Win, unde [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _210333_wwaapp {
            get {
                return ResourceManager.GetString("_210333_wwaapp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!	SWFObject v2.2 &lt;http://code.google.com/p/swfobject/&gt; 
        ///	is released under the MIT License &lt;http://www.opensource.org/licenses/mit-license.php&gt; 
        ///*/
        ///
        ///var swfobject = function() {
        ///	
        ///	var UNDEF = &quot;undefined&quot;,
        ///		OBJECT = &quot;object&quot;,
        ///		SHOCKWAVE_FLASH = &quot;Shockwave Flash&quot;,
        ///		SHOCKWAVE_FLASH_AX = &quot;ShockwaveFlash.ShockwaveFlash&quot;,
        ///		FLASH_MIME_TYPE = &quot;application/x-shockwave-flash&quot;,
        ///		EXPRESS_INSTALL_ID = &quot;SWFObjectExprInst&quot;,
        ///		ON_READY_STATE_CHANGE = &quot;onreadystatechange&quot;,
        ///		
        ///		win = window,
        ///		doc = d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _351733_swfobject2_2 {
            get {
                return ResourceManager.GetString("_351733_swfobject2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*	SWFObject v2.2 &lt;http://code.google.com/p/swfobject/&gt; 
        ///	is released under the MIT License &lt;http://www.opensource.org/licenses/mit-license.php&gt; 
        ///*/
        ///var swfobject=function(){var D=&quot;undefined&quot;,r=&quot;object&quot;,S=&quot;Shockwave Flash&quot;,W=&quot;ShockwaveFlash.ShockwaveFlash&quot;,q=&quot;application/x-shockwave-flash&quot;,R=&quot;SWFObjectExprInst&quot;,x=&quot;onreadystatechange&quot;,O=window,j=document,t=navigator,T=false,U=[h],o=[],N=[],I=[],l,Q,E,B,J=false,a=false,n,G,m=true,M=function(){var aa=typeof j.getElementById!=D&amp;&amp;typeof j.getElementsByTagName [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _351733_swfobject2_2_min {
            get {
                return ResourceManager.GetString("_351733_swfobject2_2_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var TbUtil = {
        ///    addStamp: function (A) {
        ///        return A + (A.indexOf(&quot;?&quot;) == -1 ? &quot;?&quot; : &quot;&amp;t=&quot;) + new Date().getTime().toString(32)
        ///    },
        ///    toQueryString: function (B) {
        ///        var C = [];
        ///        for (var A in B) {
        ///            C.push(encodeURIComponent(A) + &quot;=&quot; + encodeURIComponent(B[A]))
        ///        }
        ///        return C.join(&quot;&amp;&quot;)
        ///    },
        ///    selectAll: function (G, E, F) {
        ///        var D = document.getElementById(G);
        ///        if (D) {
        ///            var B = D.getElementsByTagName(&quot;input&quot;);
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _374156_common_logic {
            get {
                return ResourceManager.GetString("_374156_common_logic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     function loadScript(url, callback) {
        ///        var script = document.createElement(&quot;script&quot;);
        ///        script.type = &quot;text/javascript&quot;;
        ///        script.src = url;
        ///        if (script.readyState) {
        ///            script.onreadystatechange = function () {
        ///                if (script.readyState == &quot;loaded&quot; || script.readyState == &quot;complete&quot;) {
        ///                    script.onreadystatechange = null;
        ///                    callback();
        ///                }
        ///            };
        ///        } else {
        ///            script.onload  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _374264_repro {
            get {
                return ResourceManager.GetString("_374264_repro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        ///* © JSC &quot;PROGNOZ&quot;, 2012.
        ///*/
        ///(function(){
        ///var ObjProto,prDel,CultInfoP,enCulture,ruCulture,arCulture,zhCulture,resMngrPr,ctrlP,menuItemP,splitMenuItemP,textAreaP,ScrollBarP,ScrollBoxP,dropPanelP,TextEdtP,comboP,SpinEdtP,MonCalP,DTEditP,DTPickerP,buttonP,ribbonButtonP,menuP,mainMenuP,tabItemP,ribbonPanelP,ribbonCategoryP,ribbonP,imageListP,listItemP,listBoxP,NumEdP,htmlXamlConverterP,windowP,ColorP,CComboP,comboBoxP,numComboBoxP,confirmDialogP,dialogP,MesgPro,containerP,gridPanelP,iPanelp,iStPanelp,mem [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _515673_PP {
            get {
                return ResourceManager.GetString("_515673_PP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common = { };
        ///
        ///// 14.0.4762.1000 
        ///////////////////////////////////////////////////////////////////////////////////
        ///// Useful utilities
        ///
        ///function isUndefined(o) 
        ///{
        ///	return (o === undefined);
        ///}
        ///
        ///function isNull(o) 
        ///{
        ///	return (o === null);
        ///}
        ///
        ///function isNullOrUndefined(o) 
        ///{
        ///	return (o === null) || (o === undefined);
        ///}
        ///
        ///function defaultValue(v,d)
        ///{
        ///	return (v === undefined) ? d : v;
        ///}
        ///
        ///Sys.UI.DomEvent.prototype.preventDefault = function ()
        ///{
        ///	if (this.rawEvent.preventDefault) this.r [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string box4 {
            get {
                return ResourceManager.GetString("box4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var trackStep = 10; var trackCnt=1; function print(s) {};
        ///if(trackCnt++ % trackStep == 0) WScript.Echo(&quot;0&quot;);
        ///try{eval(&quot;&quot;);}catch(ex){}
        ///try{eval(&quot;let yupveg, tyfxkx, snfnsz, ogygge, y, ftwoms, vbobtq, tkvteo;\&quot;\\u4D41D6\&quot;;&quot;);}catch(ex){}
        ///try{eval(&quot;default xml namespace  = (Object.keys)();&quot;);}catch(ex){}
        ///try{eval(&quot;\&quot;use strict\&quot;; let (x = x = eval(\&quot;print([z1]);\&quot;), cbfoal, [] = ((\u3056 =  /x/ )), htnuii, functional = window, naxhvs) { print(x); }&quot;);}catch(ex){}
        ///try{eval(&quot;\&quot;use strict\&quot;; print((4277)); [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Bug211887 {
            get {
                return ResourceManager.GetString("Bug211887", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /\000// &lt;reference path=&quot;1433289838.jsx&quot; /&gt;
        ///;
        ///continue \u2e12;
        ///with([]._Lf[this][v][\u5891]){$[.8E+0[5]][$Rx7]%={.5E+3:[],7.1E+5:[{},,,,{},,0[this[this[this]]].\u2e06Mc],}._e[$bC._]&lt;=-(this[\u6dc9][&quot;å¯—ë»Ÿê¿ºå¨´ïºî·ºâ†”ì›¶ê¹­î¡Ÿâ½¥æ¥œï”¦â·˜&quot;])._b.$._()--;with(0x3.\u5441)try{break ;
        ///}
        ///catch(y){;
        ///;
        ///WK:{try{}
        ///catch(U6CC){}
        ///break nhb;
        ///}
        ///
        ///
        ///
        ///.
        /// </summary>
        internal static string Bug211887_2 {
            get {
                return ResourceManager.GetString("Bug211887_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /// &lt;reference path=&apos;../default.html&apos; /&gt;
        ///var test = 2;
        ///
        ///(function(){
        ///    var app = Win.Application;
        ///
        ///    try {
        ///    var foo = Windows.ApplicationModel.Activation();
        ///    foo.onActivated = function onActivated(contractId, contractActivationContext) {
        ///    };
        ///    } catch(e) {
        ///        var bar = test.|;
        ///    app.addEventListener(&apos;loaded&apos;, function() {
        ///        // Ensure that all data-win-controls are processed. If you also have
        ///        // any databinding on the page you should call: Win.Binding.process [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Bug214169 {
            get {
                return ResourceManager.GetString("Bug214169", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var trackStep = 10; var trackCnt=1; function print(s) {};
        ///if(trackCnt++ % trackStep == 0) WScript.Echo(&quot;0&quot;);
        ///try{eval(&quot;&quot;);}catch(ex){}
        ///try{eval(&quot;let yupveg, tyfxkx, snfnsz, ogygge, y, ftwoms, vbobtq, tkvteo;\&quot;\\u4D41D6\&quot;;&quot;);}catch(ex){}
        ///try{eval(&quot;default xml namespace  = (Object.keys)();&quot;);}catch(ex){}
        ///try{eval(&quot;\&quot;use strict\&quot;; let (x = x = eval(\&quot;print([z1]);\&quot;), cbfoal, [] = ((\u3056 =  /x/ )), htnuii, functional = window, naxhvs) { print(x); }&quot;);}catch(ex){}
        ///try{eval(&quot;\&quot;use strict\&quot;; print((4277)); [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Bug245383 {
            get {
                return ResourceManager.GetString("Bug245383", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var trackStep = 10; var trackCnt=1; function print(s) {};
        ///if(trackCnt++ % trackStep == 0) WScript.Echo(&quot;0&quot;);
        ///try{eval(&quot;&quot;);}catch(ex){}
        ///try{eval(&quot;print(x);&quot;);}catch(ex){}
        ///try{eval(&quot;var kqfbhx = new ArrayBuffer(12); var kqfbhx_0 = new Float64Array(kqfbhx); print(kqfbhx_0[0]); kqfbhx_0[0] = -1107533544; var kqfbhx_1 = new Uint32Array(kqfbhx); kqfbhx_1[0] = -18446744073709552000; var kqfbhx_2 = new WebGLFloatArray(kqfbhx); var kqfbhx_3 = new Int16Array(kqfbhx); ((4277));;&quot;);}catch(ex){}
        ///try{eval(&quot;/*tLoop*/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Bug245387 {
            get {
                return ResourceManager.GetString("Bug245387", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function forceDeferredParsing() {
        ///  // This forces deferred parsing by having a function that is larger than the deferred parsing threashold.
        ///  var a = 1;
        ///  a = a + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1;
        ///  a = a + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1;
        ///  a = a + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 +  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DeferredParsing {
            get {
                return ResourceManager.GetString("DeferredParsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a = 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 
        ///        1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 
        ///        1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 
        ///        1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string longExpression {
            get {
                return ResourceManager.GetString("longExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Name:        MicrosoftAjax.debug.js
        ///// Assembly:    System.Web.Extensions
        ///// Version:     4.0.0.0
        ///// FileVersion: 4.0.30205.0
        /////-----------------------------------------------------------------------
        ///// Copyright (C) Microsoft Corporation. All rights reserved.
        /////-----------------------------------------------------------------------
        ///// MicrosoftAjax.js
        ///// Microsoft AJAX Framework.
        ///
        ///Function.__typeName = &apos;Function&apos;;
        ///Function.__class = true;
        ///Function.createCallback = function Function$createCal [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MicrosoftAjax {
            get {
                return ResourceManager.GetString("MicrosoftAjax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //-----------------------------------------------------------------------
        ///// Copyright (C) Microsoft Corporation. All rights reserved.
        /////-----------------------------------------------------------------------
        ///// MicrosoftAjax.js
        ///// Microsoft AJAX Framework.
        ///
        ///
        ///Function.__typeName = &apos;Function&apos;;
        ///
        ///Function.createCallback = function Function$createCallback(method, context) {
        ///    /// &lt;param name=&quot;method&quot; type=&quot;Function&quot;&gt;&lt;/param&gt;
        ///    /// &lt;param name=&quot;context&quot; mayBeNull=&quot;true&quot;&gt;&lt;/param&gt;
        ///    /// &lt;returns  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MicrosoftAjax_Bug221337 {
            get {
                return ResourceManager.GetString("MicrosoftAjax_Bug221337", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if (VSIntellisenseExtensions) {
        ///
        ///intellisense.enableMicrosoftAjaxLog = function (logLevel) { 
        ////// &lt;summary&gt;Enables Microsoft Ajax VSIntellisense extension logging&lt;/summary&gt;
        ////// &lt;param name=&quot;logLevel&quot; type=&quot;String&quot;&gt;Acceptable values are &quot;info&quot;, &quot;warning&quot;, and &quot;error&quot;&lt;/param&gt;
        ///
        ///    intellisense.logMessage(&quot;Passed in log level is &quot; + logLevel);
        ///    if(logLevel) {
        ///        switch(logLevel.trim().toLowerCase())
        ///        {
        ///            case &quot;info&quot;:
        ///                VSIntellisenseExtensions[&quot;MicrosoftAjaxLog [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MicrosoftAjax_intellisense {
            get {
                return ResourceManager.GetString("MicrosoftAjax_intellisense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Name:        MicrosoftAjaxWebForms.debug.js
        ///// Assembly:    System.Web.Extensions
        ///// Version:     4.0.0.0
        ///// FileVersion: 4.0.30205.0
        /////-----------------------------------------------------------------------
        ///// Copyright (C) Microsoft Corporation. All rights reserved.
        /////-----------------------------------------------------------------------
        ///// MicrosoftAjaxWebForms.js
        ///// Microsoft AJAX ASP.NET WebForms Framework.
        ///Type._registerScript(&quot;MicrosoftAjaxWebForms.js&quot;, [
        ///	&quot;MicrosoftAjaxCore.js&quot;,
        ///	&quot;Mic [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MicrosoftAjaxWebForms_debug {
            get {
                return ResourceManager.GetString("MicrosoftAjaxWebForms_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        ///---
        ///MooTools: the javascript framework
        ///
        ///web build:
        /// - http://mootools.net/core/7c56cfef9dddcf170a5d68e3fb61cfd7
        ///
        ///packager build:
        /// - packager build Core/Core Core/Array Core/String Core/Number Core/Function Core/Object Core/Event Core/Browser Core/Class Core/Class.Extras Core/Slick.Parser Core/Slick.Finder Core/Element Core/Element.Style Core/Element.Event Core/Element.Dimensions Core/Fx Core/Fx.CSS Core/Fx.Tween Core/Fx.Morph Core/Fx.Transitions Core/Request Core/Request.HTML Core/Request.JSON Co [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mootools_core_1_3_2_full_compat {
            get {
                return ResourceManager.GetString("mootools_core_1_3_2_full_compat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;&lt;rss version=&quot;2.0&quot; xml:base=&quot;http://www.almasryalyoum.com/news_homepage_feed&quot; xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;&gt;
        ///  &lt;channel&gt;
        ///    &lt;title&gt;أخبار الصفحة الاولى&lt;/title&gt;
        ///    &lt;link&gt;http://www.almasryalyoum.com/news_homepage_feed&lt;/link&gt;
        ///    &lt;description&gt;&lt;/description&gt;
        ///    &lt;language&gt;ar&lt;/language&gt;
        ///        &lt;item&gt;
        /// &lt;title&gt;دول الخليج تدعو الجامعة العربية لاجتماع عاجل لـ«لوقف إراقة الدماء في سوريا»&lt;/title&gt;
        /// &lt;link&gt;http://www.almasryalyoum.com/node/504830&lt;/link&gt;
        /// &lt;d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string news_homepage_feed {
            get {
                return ResourceManager.GetString("news_homepage_feed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*  Prototype JavaScript framework, version 1.7
        /// *  (c) 2005-2010 Sam Stephenson
        /// *
        /// *  Prototype is freely distributable under the terms of an MIT-style license.
        /// *  For details, see the Prototype web site: http://www.prototypejs.org/
        /// *
        /// *--------------------------------------------------------------------------*/
        ///
        ///var Prototype = {
        ///
        ///  Version: &apos;1.7&apos;,
        ///
        ///  Browser: (function(){
        ///    var ua = navigator.userAgent;
        ///    var isOpera = Object.prototype.toString.call(window.opera) == &apos;[object Opera]&apos;; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string prototype {
            get {
                return ResourceManager.GetString("prototype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // script.aculo.us scriptaculous.js v1.9.0, Thu Dec 23 16:54:48 -0500 2010
        ///
        ///// Copyright (c) 2005-2010 Thomas Fuchs (http://script.aculo.us, http://mir.aculo.us)
        /////
        ///// Permission is hereby granted, free of charge, to any person obtaining
        ///// a copy of this software and associated documentation files (the
        ///// &quot;Software&quot;), to deal in the Software without restriction, including
        ///// without limitation the rights to use, copy, modify, merge, publish,
        ///// distribute, sublicense, and/or sell copies of the Soft [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string scriptaculous {
            get {
                return ResourceManager.GetString("scriptaculous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* DO NOT EDIT THIS FILE!
        ///		The contents of this file are dynamically generated. In order to make changes, update the
        ///		respective source files.*/
        ///
        ///// /vendor/jquery-1.4.4.js from default
        ////*
        /// * jQuery JavaScript Library v1.4.4
        /// * http://jquery.com/
        /// *
        /// * Copyright 2010, John Resig
        /// * Dual licensed under the MIT or GPL Version 2 licenses.
        /// * http://jquery.org/license
        /// *
        /// * Includes Sizzle.js
        /// * http://sizzlejs.com/
        /// * Copyright 2010, The Dojo Foundation
        /// * Released under the MIT, BSD, and GPL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string top {
            get {
                return ResourceManager.GetString("top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        ///  trblib core
        ///      Required for all trblib plugins. Contains sub-libraries require, run, util, fn, and plugins.
        ///          
        ///              trblib require
        ///                    Loads JavaScript / CSS files dynamically.
        ///                        
        ///                            trblib run
        ///                                  Event runner consolidating multiple events with a common handler. Allows custom events.
        ///                                      
        ///                                          trlib util
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string trblib {
            get {
                return ResourceManager.GetString("trblib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 网页 资讯 商品 团购 音乐 图片 地图 知识堂 淘宝商城 淘网址 搜 索连衣裙 针织衫 靴子 皮衣 羽绒服 围巾 低帮鞋 牛仔裤 卫衣 马夹 瘦腿袜 腰带 包袋 棉衣 家居服 风衣 帽子 男装热卖 卫衣 衬衫 中裤 休闲鞋 长袖衬衫 休闲西装 开衫 牛仔裤 商务皮鞋 太阳镜 斜挎包 西裤 ZIPPO 手包 皮带 资讯 评论 社会 军事 海外 财经 理财 股票 基金 行情 娱乐 明星 电影 电视 鲜图 体育 NBA 彩票 足球 中超 时尚 服饰 美容 情感 奢华 社区 论坛 邮箱 知识堂 汽车 旅游 数码 科技 家居 育儿 文化 教育 历史 读书 公益 艺术 健康 星座 乐玩 宠物 团聚 视频 聚方便 优惠券 推荐：巨优惠 旺旺 实用查询 淘女郎 专题 淘宝天下 淘江湖 工具 天下网商 调查  全部服务» 2011年10月14日 星期五 时空对话：上访的路上往往没有青天上访这根最后的救命稻草还有没有用，它能否唤回一片法治彰显的青天…[详细]当向钱看的医生遇到疑心的病人 高衙内阴魂为何千年不散 更多»  新疆哈密遭风雪袭击 两省道关闭车辆滞留10月12日，新疆哈密遭遇风雪降温天气，两省道积雪结冰被迫关闭…[详细 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string unicode {
            get {
                return ResourceManager.GetString("unicode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (function () {
        ///var rootNamespace = this;
        ///var dp = null;
        ///var dpg = null;
        ///var eventParamOf = null;
        ///if (Object.defineProperty == undefined) {
        ///    var shadowableMembers = [&apos;apply&apos;, &apos;call&apos;, &apos;hasOwnProperty&apos;, &apos;isPrototypeOf&apos;, &apos;propertyIsEnumerable&apos;, &apos;toLocalString&apos;, &apos;toString&apos;, &apos;valueOf&apos;];
        ///    shadowableMembers.contains = function (name) {
        ///        for (var i = 0; i &lt; shadowableMembers.length; i++) {
        ///            if (shadowableMembers[i] == name) { return true; }
        ///        }
        ///        return false;
        ///    };
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string winrt {
            get {
                return ResourceManager.GetString("winrt", resourceCulture);
            }
        }
    }
}
