//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirectAuthorCheckinTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WinJSTestFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WinJSTestFiles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DirectAuthorCheckinTests.WinJSTestFiles", typeof(WinJSTestFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /// &lt;loc filename=&quot;metadata\base_loc_oam.xml&quot; format=&quot;messagebundle&quot; /&gt;
        ////// &lt;reference path=&apos;base.js&apos; /&gt;
        /// 
        ////*
        ///  © Microsoft. All rights reserved.
        ///
        ///  This library is supported for use in Windows Tailored Apps only.
        ///
        ///  Build: 6.2.8072.0 
        ///  Version: 0.5 
        ///*/
        /// 
        ///
        ///
        ///(function (global, undefined) {
        ///
        ///    function initializeProperties(target, members) {
        ///        var keys = Object.keys(members);
        ///        var properties;
        ///        var i, len;
        ///        for (i = 0, len = keys.length; i &lt; len; i++) {
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _base {
            get {
                return ResourceManager.GetString("_base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /// &lt;loc filename=&quot;metadata\animations_loc_oam.xml&quot; format=&quot;messagebundle&quot; /&gt;
        ////// &lt;reference path=&apos;base.js&apos; /&gt;
        ////// &lt;reference path=&apos;ui.js&apos; /&gt;
        /// 
        ////*
        ///  © Microsoft. All rights reserved.
        ///
        ///  This library is supported for use in Windows Tailored Apps only.
        ///
        ///  Build: 6.2.8072.0 
        ///  Version: 0.5 
        ///*/
        /// 
        ///
        ///WinJS.Namespace.define(&quot;WinJS.UI&quot;, {});
        ///
        ///(function (WinJS) {
        ///var thisWinUI = WinJS.UI;  
        ///var mstransform = &quot;-ms-transform&quot;;
        ///
        ///var OffsetArray = WinJS.Class.define (function (offset, defOffset) {
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string animations {
            get {
                return ResourceManager.GetString("animations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /// &lt;loc filename=&quot;metadata\binding_loc_oam.xml&quot; format=&quot;messagebundle&quot; /&gt;
        ////// &lt;reference path=&apos;base.js&apos; /&gt;
        ////// &lt;reference path=&apos;ui.js&apos; /&gt;
        ////// &lt;reference path=&apos;binding.js&apos; /&gt;
        /// 
        ////*
        ///  © Microsoft. All rights reserved.
        ///
        ///  This library is supported for use in Windows Tailored Apps only.
        ///
        ///  Build: 6.2.8072.0 
        ///  Version: 0.5 
        ///*/
        /// 
        ///
        ///
        ///(function (global, undefined) {
        ///
        ////*
        ///    See comment for data-win-options attribute grammar for context.
        ///
        ///    Syntactic grammar for the value of the data-win-bind  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string binding {
            get {
                return ResourceManager.GetString("binding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /// &lt;loc filename=&quot;metadata\controls_loc_oam.xml&quot; format=&quot;messagebundle&quot; /&gt;
        ////// &lt;reference path=&apos;base.js&apos; /&gt;
        ////// &lt;reference path=&apos;ui.js&apos; /&gt;
        ////// &lt;reference path=&apos;animations.js&apos; /&gt;
        /// 
        ////*
        ///  © Microsoft. All rights reserved.
        ///
        ///  This library is supported for use in Windows Tailored Apps only.
        ///
        ///  Build: 6.2.8072.0 
        ///  Version: 0.5 
        ///*/
        /// 
        ///
        ///
        ///(function (WinJS, undefined) {
        ///    var Control = WinJS.Class.define(null, {
        ///        raiseEvent: function (type, details) {
        ///            /// &lt;summary locid=&quot;170&quot;&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string controls {
            get {
                return ResourceManager.GetString("controls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /// &lt;loc filename=&quot;Metadata\base_loc_oam.xml&quot; format=&quot;messagebundle&quot; /&gt;
        ////*!
        ///  © Microsoft. All rights reserved.
        ///
        ///  This library is supported for use in Windows apps only.
        ///
        ///  Build: 1.0.8370.0.winmain_win8rc.120428-1335
        ///  
        ///  Version: Microsoft.WinJS.1.0.RC
        ///*/
        ////// &lt;reference path=&quot;ms-appx://Microsoft.WinJS.1.0.RC/js/base.js&quot; /&gt;
        ///(function baseInit(global, undefined) {
        ///    &quot;use strict&quot;;
        ///
        ///    function initializeProperties(target, members) {
        ///        var keys = Object.keys(members);
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string latest_base {
            get {
                return ResourceManager.GetString("latest_base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /// &lt;loc filename=&quot;Metadata\ui_loc_oam.xml&quot; format=&quot;messagebundle&quot; /&gt;
        ////*!
        ///  © Microsoft. All rights reserved.
        ///
        ///  This library is supported for use in Windows apps only.
        ///
        ///  Build: 1.0.8370.0.winmain_win8rc.120428-1335
        ///  
        ///  Version: Microsoft.WinJS.1.0.RC
        ///*/
        ////// &lt;reference path=&quot;ms-appx://Microsoft.WinJS.1.0.RC/js/base.js&quot; /&gt;
        ////// &lt;reference path=&quot;ms-appx://Microsoft.WinJS.1.0.RC/js/ui.js&quot; /&gt;
        ///
        ///
        ///
        ///(function animationsInit(WinJS) {
        ///    &quot;use strict&quot;;
        ///
        ///var thisWinUI = WinJS.UI;
        ///var ms [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string latest_ui {
            get {
                return ResourceManager.GetString("latest_ui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /// &lt;loc filename=&quot;metadata\res_loc_oam.xml&quot; format=&quot;messagebundle&quot; /&gt;
        ////// &lt;reference path=&apos;base.js&apos; /&gt;
        /// 
        ////*
        ///  © Microsoft. All rights reserved.
        ///
        ///  This library is supported for use in Windows Tailored Apps only.
        ///
        ///  Build: 6.2.8072.0 
        ///  Version: 0.5 
        ///*/
        /// 
        ///
        ///
        ///(function (WinJS, undefined) {    
        ///
        ///    var readyComplete = false;
        ///    var resourceMap;
        ///    var resourceLoader;
        ///
        ///    function processAllImpl(rootElement) {
        ///        WinJS.Resources._processAllImpl(rootElement);
        ///        return WinJS.P [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string res {
            get {
                return ResourceManager.GetString("res", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /// &lt;loc filename=&quot;metadata\ui_loc_oam.xml&quot; format=&quot;messagebundle&quot; /&gt;
        ////// &lt;reference path=&apos;base.js&apos; /&gt;
        /// 
        ////*
        ///  © Microsoft. All rights reserved.
        ///
        ///  This library is supported for use in Windows Tailored Apps only.
        ///
        ///  Build: 6.2.8072.0 
        ///  Version: 0.5 
        ///*/
        /// 
        ///
        ///
        ///(function (WinJS, undefined) {
        ///
        ///    var DOMEventMixin = {
        ///        _domElement: null,
        ///        
        ///        addEventListener: function (type, listener, useCapture) {
        ///            /// &lt;summary locid=&quot;1&quot;&gt;
        ///            /// Adds an event listener [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ui {
            get {
                return ResourceManager.GetString("ui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /// &lt;loc filename=&quot;metadata\uicollections_loc_oam.xml&quot; format=&quot;messagebundle&quot; /&gt;
        ////// &lt;reference path=&apos;uicollections.js&apos; /&gt;
        /// 
        ////*
        ///  © Microsoft. All rights reserved.
        ///
        ///  This library is supported for use in Windows Tailored Apps only.
        ///
        ///  Build: 6.2.8072.0 
        ///  Version: 0.5 
        ///*/
        /// 
        ///
        ///WinJS.UI._setTimeout = function (callback, delay) { 
        ///    return window.setTimeout(callback, delay);
        ///};
        ///
        ///
        ///(function (WinJS) {
        ///    var thisWinUI = WinJS.UI;
        ///    var utilities = WinJS.Utilities;
        ///    var animation = Win [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string uicollections {
            get {
                return ResourceManager.GetString("uicollections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /// &lt;loc filename=&quot;metadata\wwaapp_loc_oam.xml&quot; format=&quot;messagebundle&quot; /&gt;
        ////// &lt;reference path=&apos;base.js&apos; /&gt;
        ////// &lt;reference path=&apos;wwaapp.js&apos; /&gt;
        ////// &lt;reference winrt=&apos;true&apos;  /&gt;
        /// 
        ////*
        ///  © Microsoft. All rights reserved.
        ///
        ///  This library is supported for use in Windows Tailored Apps only.
        ///
        ///  Build: 6.2.8072.0 
        ///  Version: 0.5 
        ///*/
        /// 
        ///
        ///
        ///(function (global, WinJS, undefined) {
        ///    var checkpointET = &quot;checkpoint&quot;, 
        ///        unloadET = &quot;unload&quot;, 
        ///        mainwindowactivatedET = &quot;mainwindowactivated&quot;, 
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string wwaapp {
            get {
                return ResourceManager.GetString("wwaapp", resourceCulture);
            }
        }
    }
}
