//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChakraUnitTestTelemetry {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FBL_IE_SCRIPT_DEV;FBL_IE_SCRIPT;FBL_IE_DEV2_DEV;FBL_IE_MC;FBL_IE_MC_DEV;WINBLUE_R" +
            "TM_IE;WINBLUE_GDR_IE")]
        public string SnapBranchesToScan {
            get {
                return ((string)(this["SnapBranchesToScan"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\iesnap\\queue")]
        public string SnapLogsRootFolder {
            get {
                return ((string)(this["SnapLogsRootFolder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\bpt-scratch\\UserFiles\\cmorse\\Tools\\ChakraUnitTestTelemetry\\Unhandled Exceptions" +
            "")]
        public string UnhandledExceptionFolder {
            get {
                return ((string)(this["UnhandledExceptionFolder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\bpt-scratch\\UserFiles\\cmorse\\Tools\\ChakraUnitTestTelemetry\\UserLogs")]
        public string UserLogsCopyToFolder {
            get {
                return ((string)(this["UserLogsCopyToFolder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000000")]
        public int MaxLogQueueEntryCount {
            get {
                return ((int)(this["MaxLogQueueEntryCount"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public uint MaxUploadAttemptCount {
            get {
                return ((uint)(this["MaxUploadAttemptCount"]));
            }
        }
    }
}
