//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChakraUnitTestTelemetry.Test {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceBin {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceBin() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChakraUnitTestTelemetry.Test.ResourceBin", typeof(ResourceBin).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///08/16/2013 00:22:52:441 [Daemon] v 2.1.5.19 ********Task id 9302411 run On Machine IESNAP-BLD38 ******
        ///
        ///08/16/2013 00:22:52:457 [Daemon] Successfully launch \\IESnap\Snap\bin\razzletasks.cmd %EnlistRoot%\FBL_IE_SCRIPT_DEV check_unit_test FBL_IE_SCRIPT_DEV amd64 fre \\iesnap\snap\config\fbl_ie_script_dev.cfg.xml 90209 112721 jscript with processid: 6916
        /// Setting up Razzle amd64 fre
        ///
        ///Checking UnitTest FBL_IE_SCRIPT_DEV amd64 fre
        ///Running S:\FBL_IE_SCRIPT_DEV\inetcore\tools\unittest\ieutscan\ieutscan.cm [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RunJScriptUnitTests_IESNAP_BLD38_amd64_fre {
            get {
                return ResourceManager.GetString("RunJScriptUnitTests_IESNAP_BLD38_amd64_fre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///08/22/2013 20:30:54:566 [Daemon] v 2.1.5.19 ********Task id 9341515 run On Machine IESNAP-BLD55 ******
        ///
        ///08/22/2013 20:30:54:582 [Daemon] Successfully launch \\IESnap\Snap\bin\razzletasks.cmd %EnlistRoot%\FBL_IE_SCRIPT_DEV check_unit_test FBL_IE_SCRIPT_DEV x86 chk \\iesnap\snap\config\fbl_ie_script_dev.cfg.xml 90410 112952 jscript with processid: 7808
        /// Setting up Razzle x86 chk
        ///
        ///Checking UnitTest FBL_IE_SCRIPT_DEV x86 chk
        ///Running S:\FBL_IE_SCRIPT_DEV\inetcore\tools\unittest\ieutscan\ieutscan.cmd
        ///DEB [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SNAP_Failure_FBL_IE_SCRIPT_DEV {
            get {
                return ResourceManager.GetString("SNAP_Failure_FBL_IE_SCRIPT_DEV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3&gt;Running executable tests in directory InlineCaches
        ///6&gt;+++ InlineCaches (t5.js () exe) +++
        ///6&gt;Running &apos;jshost.exe -bvt   -DumpOnCrash -maxinterpretcount:1 -bgjit- -dynamicprofilecache:profile.dpl.UnnamedTest74  X:\fbl_ie_script_dev\inetcore\jscript\unittest\InlineCaches\t5.js  &gt;testout4 2&gt;&amp;1&apos;
        ///4&gt;+++ InlineCaches (t3.js ( -version:3) exe) +++
        ///4&gt;Running &apos;jshost.exe -bvt   -DumpOnCrash -maxinterpretcount:1 -bgjit- -dynamicprofilecache:profile.dpl.UnnamedTest72  -version:3 X:\fbl_ie_script_dev\inetcore\jscrip [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string USER_rl_full {
            get {
                return ResourceManager.GetString("USER_rl_full", resourceCulture);
            }
        }
    }
}
