WScript.RegisterCrossThreadInterfacePS();

var x = WScript.LoadScriptFile("testObjects.js", "crossthread");
WScript.LoadScriptFile("testObjects.js");

WScript.Echo(x.testNumber1.toString());
WScript.Echo(x.testNumber1.toLocaleString());
WScript.Echo(x.testNumber1.valueOf());
WScript.Echo(x.testNumber1.valueOf() == x.testNumber1);
WScript.Echo(x.testNumber1.toFixed());
WScript.Echo(x.testNumber1.toExponential());
WScript.Echo(x.testNumber1.toPrecision());
WScript.Echo();
WScript.Echo(x.testNumberObject1.toString());
WScript.Echo(x.testNumberObject1.toLocaleString());
WScript.Echo(x.testNumberObject1.valueOf());
WScript.Echo(x.testNumberObject1.valueOf() == x.testNumber1);
WScript.Echo(x.testNumberObject1.toFixed());
WScript.Echo(x.testNumberObject1.toExponential());
WScript.Echo(x.testNumberObject1.toPrecision());
WScript.Echo();
WScript.Echo(Number.prototype.toString.call(x.testNumber1));
WScript.Echo(Number.prototype.toLocaleString.call(x.testNumber1));
WScript.Echo(Number.prototype.valueOf.call(x.testNumber1));
WScript.Echo(Number.prototype.valueOf.call(x.testNumber1) == x.testNumber1);
WScript.Echo(Number.prototype.toFixed.call(x.testNumber1));
WScript.Echo(Number.prototype.toExponential.call(x.testNumber1));
WScript.Echo(Number.prototype.toPrecision.call(x.testNumber1));
WScript.Echo();
WScript.Echo(Number.prototype.toString.call(x.testNumberObject1));
WScript.Echo(Number.prototype.toLocaleString.call(x.testNumberObject1));
WScript.Echo(Number.prototype.valueOf.call(x.testNumberObject1));
WScript.Echo(Number.prototype.valueOf.call(x.testNumberObject1) == x.testNumberObject1);
WScript.Echo(Number.prototype.toFixed.call(x.testNumberObject1));
WScript.Echo(Number.prototype.toExponential.call(x.testNumberObject1));
WScript.Echo(Number.prototype.toPrecision.call(x.testNumberObject1));
WScript.Echo();
WScript.Echo(x.Number.prototype.toString.call(testNumber1));
WScript.Echo(x.Number.prototype.toLocaleString.call(testNumber1));
WScript.Echo(x.Number.prototype.valueOf.call(testNumber1));
WScript.Echo(x.Number.prototype.valueOf.call(testNumber1) == testNumber1);
WScript.Echo(x.Number.prototype.toFixed.call(testNumber1));
WScript.Echo(x.Number.prototype.toExponential.call(testNumber1));
WScript.Echo(x.Number.prototype.toPrecision.call(testNumber1));
WScript.Echo();
WScript.Echo(x.Number.prototype.toString.call(testNumberObject1));
WScript.Echo(x.Number.prototype.toLocaleString.call(testNumberObject1));
WScript.Echo(x.Number.prototype.valueOf.call(testNumberObject1));
WScript.Echo(x.Number.prototype.valueOf.call(testNumberObject1) == testNumberObject1);
WScript.Echo(x.Number.prototype.toFixed.call(testNumberObject1));
WScript.Echo(x.Number.prototype.toExponential.call(testNumberObject1));
WScript.Echo(x.Number.prototype.toPrecision.call(testNumberObject1));
WScript.Echo();
