//-------------------------------------------------------------------------------------------------------
// Copyright (C) Microsoft. All rights reserved.
//-------------------------------------------------------------------------------------------------------

// Array builtins
ENTRY_BUILTIN(ES5, ArrayisArray)
ENTRY_BUILTIN(ES5, ArrayIndexOf)
ENTRY_BUILTIN(ES5, ArrayIncludes)
ENTRY_BUILTIN(ES5, ArrayEvery)
ENTRY_BUILTIN(ES5, ArrayFilter)
ENTRY_BUILTIN(ES5, ArrayForEach)
ENTRY_BUILTIN(ES5, ArrayLastIndexOf)
ENTRY_BUILTIN(ES5, ArrayMap)
ENTRY_BUILTIN(ES5, ArrayReduce)
ENTRY_BUILTIN(ES5, ArrayReduceRight)
ENTRY_BUILTIN(ES5, ArraySome)

// ArrayBuffer builtins
ENTRY_BUILTIN(ES6, ArrayBufferTransfer)

// Object builtins
ENTRY_BUILTIN(ES5, ObjectDefineProperties)
ENTRY_BUILTIN(ES5, ObjectCreate)
ENTRY_BUILTIN(ES5, ObjectSeal)
ENTRY_BUILTIN(ES5, ObjectFreeze)
ENTRY_BUILTIN(ES5, ObjectPreventExtension)
ENTRY_BUILTIN(ES5, ObjectIsSealed)
ENTRY_BUILTIN(ES5, ObjectIsFrozen)
ENTRY_BUILTIN(ES5, ObjectIsExtensible)
ENTRY_BUILTIN(ES5, ObjectGetOwnPropertyNames)
ENTRY_BUILTIN(ES5, ObjectGetPrototypeOf)
ENTRY_BUILTIN(ES5, ObjectKeys)
ENTRY_BUILTIN(ES7, ObjectValues)
ENTRY_BUILTIN(ES7, ObjectEntries)

ENTRY_BUILTIN(ES5, DateToISOString)
ENTRY_BUILTIN(ES5, FunctionBind)
ENTRY_BUILTIN(ES5, StringTrim)
ENTRY_BUILTIN(ES6, GetOwnPropertySymbols)

//ES6 builtins
//Math builtins
ENTRY_BUILTIN(ES6, Log10)
ENTRY_BUILTIN(ES6, Log1p)
ENTRY_BUILTIN(ES6, Log2)
ENTRY_BUILTIN(ES6, Expm1)
ENTRY_BUILTIN(ES6, Sinh)
ENTRY_BUILTIN(ES6, Cosh)
ENTRY_BUILTIN(ES6, Tanh)
ENTRY_BUILTIN(ES6, Asinh)
ENTRY_BUILTIN(ES6, Acosh)
ENTRY_BUILTIN(ES6, Atanh)
ENTRY_BUILTIN(ES6, Hypot)
ENTRY_BUILTIN(ES6, Cbrt)
ENTRY_BUILTIN(ES6, Trunc)
ENTRY_BUILTIN(ES6, Sign)
ENTRY_BUILTIN(ES6, Imul)
ENTRY_BUILTIN(ES6, Clz32)
ENTRY_BUILTIN(ES6, Fround)

// Number builtins
ENTRY_BUILTIN(ES6, IsNaN)
ENTRY_BUILTIN(ES6, IsFinite)
ENTRY_BUILTIN(ES6, IsInteger)
ENTRY_BUILTIN(ES6, IsSafeInteger)

//String builtins
ENTRY_BUILTIN(ES6, StartsWith)
ENTRY_BUILTIN(ES6, EndsWith)
ENTRY_BUILTIN(ES6, Contains)
ENTRY_BUILTIN(ES6, Repeat)
ENTRY_BUILTIN(ES7, PadStart)
ENTRY_BUILTIN(ES7, PadEnd)

// RegEx builtins
ENTRY_BUILTIN(ES6, RegexSymbolMatch)
ENTRY_BUILTIN(ES6, RegexSymbolSearch)
ENTRY_BUILTIN(ES6, RegexSymbolReplace)
ENTRY_BUILTIN(ES6, RegexSymbolSplit)

//Ctors
ENTRY_BUILTIN(ES6, Proxy)
ENTRY_BUILTIN(ES6, Symbol)
ENTRY_BUILTIN(ES6, Map)
ENTRY_BUILTIN(ES6, WeakMap)
ENTRY_BUILTIN(ES6, WeakSet)
ENTRY_BUILTIN(ES6, Set)
ENTRY_BUILTIN(ES6, Promise)

//TypedArray Methods
ENTRY_BUILTIN(TA, TAFrom)
ENTRY_BUILTIN(TA, TAOf)
ENTRY_BUILTIN(TA, TACopyWithin)
ENTRY_BUILTIN(TA, TAEntries)
ENTRY_BUILTIN(TA, TAEvery)
ENTRY_BUILTIN(TA, TAFilter)
ENTRY_BUILTIN(TA, TAFill)
ENTRY_BUILTIN(TA, TAFind)
ENTRY_BUILTIN(TA, TAFindIndex)
ENTRY_BUILTIN(TA, TAForEach)
ENTRY_BUILTIN(TA, TAIndexOf)
ENTRY_BUILTIN(TA, TAIncludes)
ENTRY_BUILTIN(TA, TAJoin)
ENTRY_BUILTIN(TA, TAKeys)
ENTRY_BUILTIN(TA, TALastIndexOf)
ENTRY_BUILTIN(TA, TAMap)
ENTRY_BUILTIN(TA, TAReduce)
ENTRY_BUILTIN(TA, TAReduceRight)
ENTRY_BUILTIN(TA, TAReverse)
ENTRY_BUILTIN(TA, TASome)
ENTRY_BUILTIN(TA, TASort)
ENTRY_BUILTIN(TA, TASubArray)
ENTRY_BUILTIN(TA, TAValues)

// Language Features
ENTRY_LANGFEATURE(ES6, Let)
ENTRY_LANGFEATURE(ES6, Lambda)
ENTRY_LANGFEATURE(ES6, StrictModeFunction)
ENTRY_LANGFEATURE(ES6, Super)
ENTRY_LANGFEATURE(ES6, Class)
ENTRY_LANGFEATURE(ES6, AsmJSFunction)
ENTRY_LANGFEATURE(ES6, StringTemplates)
ENTRY_LANGFEATURE(ES6, Const)
ENTRY_LANGFEATURE(ES6, Generator)
ENTRY_LANGFEATURE(ES6, Rest)
ENTRY_LANGFEATURE(ES6, SpreadFeature)
ENTRY_LANGFEATURE(ES6, UnicodeRegexFlag)
ENTRY_LANGFEATURE(ES6, StickyRegexFlag)
ENTRY_LANGFEATURE(ES6, DefaultArgFunction)

// ES7 stuff, formerly in BuiltinsDatabase.inc
ENTRY_BUILTIN(ES7, Array, Prototype, contains)
ENTRY_BUILTIN(ES7, Array, Prototype, includes)
ENTRY_BUILTIN(ES7, Array, Constructor, observe)
ENTRY_BUILTIN(ES7, Array, Constructor, unobserve)
ENTRY_BUILTIN(ES7, ArrayBuffer, Constructor, transfer)
ENTRY_BUILTIN(ES7, Float32Array, Prototype, includes)
ENTRY_BUILTIN(ES7, Float64Array, Prototype, includes)
ENTRY_BUILTIN(ES7, Int16Array, Prototype, includes)
ENTRY_BUILTIN(ES7, Int32Array, Prototype, includes)
ENTRY_BUILTIN(ES7, Int8Array, Prototype, includes)
ENTRY_BUILTIN(ES7, Map, Prototype, toJSON)
ENTRY_BUILTIN(ES7, Object, Constructor, getOwnPropertyDescriptors)
ENTRY_BUILTIN(ES7, Object, Constructor, observe)
ENTRY_BUILTIN(ES7, Object, Constructor, unobserve)
ENTRY_BUILTIN(ES7, RegExp, Constructor, escape)
ENTRY_BUILTIN(ES7, Set, Prototype, toJSON)
ENTRY_BUILTIN(ES7, String, Prototype, at)
ENTRY_BUILTIN(ES7, String, Prototype, leftPad)
ENTRY_BUILTIN(ES7, String, Prototype, lPad)
ENTRY_BUILTIN(ES7, String, Prototype, padLeft)
ENTRY_BUILTIN(ES7, String, Prototype, padRight)
ENTRY_BUILTIN(ES7, String, Prototype, rightPad)
ENTRY_BUILTIN(ES7, String, Prototype, rPad)
ENTRY_BUILTIN(ES7, String, Prototype, substr, Proprietary)
ENTRY_BUILTIN(ES7, String, Prototype, trimLeft)
ENTRY_BUILTIN(ES7, String, Prototype, trimRight)
ENTRY_BUILTIN(ES7, Uint16Array, Prototype, includes)
ENTRY_BUILTIN(ES7, Uint32Array, Prototype, includes)
ENTRY_BUILTIN(ES7, Uint8Array, Prototype, includes)
ENTRY_BUILTIN(ES7, Uint8ClampedArray, Prototype, includes)