
function _CoreClrCalculateNewVersion(versionh)
{
    var today = new Date();
    var firstDay=new Date(2006,7,30);
    var days=Math.floor((today - firstDay)/(1000*60*60*24));

    var oldrpt;
    var oldrup;

    var file = FSOOpenTextFile(versionh,1);
    while (!file.AtEndOfStream) 
    {
   

	var line = file.ReadLine();
        if (line.match(/^\s*#define\s+rup\s+(\d*)\s*$/))
        {
            oldrup=RegExp.$1;
        }
        else
        if (line.match(/^\s*#define\s+rpt\s+(\d*)\s*$/))
        {
            oldrpt=RegExp.$1;        
        }
    }
    file.Close();


    var retval = new Object;
    retval.major=2;
    retval.minor=0;
    retval.revision=new Object;
    retval.revision.major=days;
    retval.revision.minor=0;


    if (days == oldrup && oldrpt != undefined)
        retval.revision.minor=Number(oldrpt)+1;

    
    return retval;
}

function _coreClrUpdateVersionH(filename,version)
{
 
    file = FSOOpenTextFile(filename,2);
    file.WriteLine("//Auto generated by coreClrUpdateBuildVersion, "+Date());
    file.WriteLine("#define rmj "+version.major);
    file.WriteLine("#define rmm "+version.minor);
    file.WriteLine("#define rup "+version.revision.major);
    file.WriteLine("#define rpt "+version.revision.minor);
    file.Close();

}

function _coreClrUpdateCscConfig(fileName, version)
{

    file = FSOOpenTextFile(fileName,2);
    file.WriteLine("<!-- Auto generated by coreClrUpdateBuildVersion, "+Date()+" -->");
    file.WriteLine("<configuration>");
    file.WriteLine("\t<startup>");
    file.WriteLine("\t\t<requiredRuntime imageVersion=\"v"+version.major+"."+version.minor+"."+version.revision.major+"\"/>");
    file.WriteLine("\t</startup>");
    file.WriteLine("</configuration>");
    file.Close();

}





function _coreClrVersionFiles()
{

    var retval=new Object();
/*  disable modification of CSC files so the produced mscorlib could be used with v2.0
    retval.CSC=new Array(
	srcBaseFromScript()+"\\tools\\x86_ia64\\vc\\bin\\csc.exe.config",
	srcBaseFromScript()+"\\tools\\x86_amd64\\vc\\bin\\csc.exe.config",
	srcBaseFromScript()+"\\tools\\x86\\managed\\v2.0\\csc.exe.config"
	);
*/
    retval.versionh=srcBaseFromScript()+"\\ndp\\inc\\version\\version.h"

    retval.all=new Array();
    for (i in retval.CSC)
	retval.all[retval.all.length]=retval.CSC[i];
    retval.all[retval.all.length]=retval.versionh;
    return retval;
}

function coreClrUpdateBuildVersion()
{
    var files=_coreClrVersionFiles();
    var version=_CoreClrCalculateNewVersion(files.versionh);

    logMsg(LogScript, LogInfo, "CoreCLR: new build - ",version.major,".",version.minor,".",version.revision.major,".",version.revision.minor,"\n");


    _coreClrUpdateVersionH(files.versionh,version);
    for (config in files.CSC)
    	_coreClrUpdateCscConfig(files.CSC[config], version);

    return  0;
}