jc.exe -bvt -NoNative -Loop:10 \release\unittest\SunSpider\3d-cube.js >>\release\unittest\sunspiderresults.txt
jc.exe -bvt -NoNative -Loop:10 \release\unittest\SunSpider\3d-morph.js >>\release\unittest\sunspiderresults.txt
jc.exe -bvt -NoNative -Loop:10 \release\unittest\SunSpider\3d-raytrace.js >>\release\unittest\sunspiderresults.txt
jc.exe -bvt -NoNative -Loop:10 \release\unittest\SunSpider\access-binary-trees.js >>\release\unittest\sunspiderresults.txt
jc.exe -bvt -NoNative -Loop:10 \release\unittest\SunSpider\access-fannkuch.js >>\release\unittest\sunspiderresults.txt
jc.exe -bvt -NoNative -Loop:10 \release\unittest\SunSpider\access-nbody.js >>\release\unittest\sunspiderresults.txt
jc.exe -bvt -NoNative -Loop:10 \release\unittest\SunSpider\access-nsieve.js >>\release\unittest\sunspiderresults.txt
jc.exe -bvt -NoNative -Loop:10 \release\unittest\SunSpider\bitops-3bit-bits-in-byte.js >>\release\unittest\sunspiderresults.txt
jc.exe -bvt -NoNative -Loop:10 \release\unittest\SunSpider\bitops-bits-in-byte.js >>\release\unittest\sunspiderresults.txt
jc.exe -bvt -NoNative -Loop:10 \release\unittest\SunSpider\bitops-bitwise-and.js >>\release\unittest\sunspiderresults.txt
jc.exe -bvt -NoNative -Loop:10 \release\unittest\SunSpider\bitops-nsieve-bits.js >>\release\unittest\sunspiderresults.txt
jc.exe -bvt -NoNative -Loop:10 \release\unittest\SunSpider\controlflow-recursive.js >>\release\unittest\sunspiderresults.txt
jc.exe -bvt -NoNative -Loop:10 \release\unittest\SunSpider\crypto-aes.js >>\release\unittest\sunspiderresults.txt
jc.exe -bvt -NoNative -Loop:10 \release\unittest\SunSpider\crypto-md5.js >>\release\unittest\sunspiderresults.txt
jc.exe -bvt -NoNative -Loop:10 \release\unittest\SunSpider\crypto-sha1.js >>\release\unittest\sunspiderresults.txt
jc.exe -bvt -NoNative -Loop:10 \release\unittest\SunSpider\date-format-tofte.js >>\release\unittest\sunspiderresults.txt
jc.exe -bvt -NoNative -Loop:10 \release\unittest\SunSpider\date-format-xparb.js >>\release\unittest\sunspiderresults.txt
jc.exe -bvt -NoNative -Loop:10 \release\unittest\SunSpider\math-cordic.js >>\release\unittest\sunspiderresults.txt
jc.exe -bvt -NoNative -Loop:10 \release\unittest\SunSpider\math-partial-sums.js >>\release\unittest\sunspiderresults.txt
jc.exe -bvt -NoNative -Loop:10 \release\unittest\SunSpider\math-spectral-norm.js >>\release\unittest\sunspiderresults.txt
jc.exe -bvt -NoNative -Loop:10 \release\unittest\SunSpider\regexp-dna.js >>\release\unittest\sunspiderresults.txt
jc.exe -bvt -NoNative -Loop:10 \release\unittest\SunSpider\string-base64.js >>\release\unittest\sunspiderresults.txt
jc.exe -bvt -NoNative -Loop:10 \release\unittest\SunSpider\string-fasta.js >>\release\unittest\sunspiderresults.txt
jc.exe -bvt -NoNative -Loop:10 \release\unittest\SunSpider\string-tagcloud.js >>\release\unittest\sunspiderresults.txt
jc.exe -bvt -NoNative -Loop:10 \release\unittest\SunSpider\string-unpack-code.js >>\release\unittest\sunspiderresults.txt
jc.exe -bvt -NoNative -Loop:10 \release\unittest\SunSpider\string-validate-input.js >>\release\unittest\sunspiderresults.txt
