//
//    Copyright (C) Microsoft.  All rights reserved.
//
#ifdef DEBUG
#define TRACK_TYPE_STATS 1
#endif

#include "Names.h"
#include "ScriptDirectAuthor.h"
#include "AuthorDiagnostics.h"
#include "AuthUtils.h"
#include "authorstr.h"
#include "SimpleComObject.h"
#include "ExecutionStop.h"
#include "PNodeSerializer.h"
#include "AuthoringProbe.h"
#include "AuthorHelpers.h"
#include "FindChildWalkerPolicy.h"
#include "ParseNodeFinder.h"
#include "TokenEnumerator.h"
#include "Colorizer.h"
#include "RegionSet.h"
#include "TaskCommentSet.h"
#include "IdentifierAddPolicy.h"
#include "TreeValidator.h"
#include "CleanTree.h"
#include "RewriteTreeHelpers.h"
#include "ASTBuilder.h"
#include "GuardingVisitor.h"
#include "AddLoopGuards.h"
#include "DirectExecution.h"
#include "AddNestedCalls.h"
#include "HoistSubsumedFunctions.h"
#include "VisitorComposer.h"
#include "MessageSet.h"
#include "CommentTable.h"
#include "MemoryAuthoringFile.h"
#include "AuthoringFactory.h"
#include "Completions.h"
#include "DocComments.h"
#include "JsDocCommentsParser.h"
#include "ParseNodeTree.h"
#include "AuthoringFileText.h"
#include "AsyncRequests.h"
#include "AuthoringFileHandle.h"
#include "FunctionHelpInfo.h"
#include "AuthorExecUtils.h"
#include "ScriptContextPath.h"
#include "ScriptContextManager.h"
#include "AuthoringServicesInfo.h"
#include "ParseNodeCursor.h"
#include "AuthorScopeConverter.h"
#include "SymbolHelp.h"
#include "FileAuthoring.h"
#include "JsValueDoc.h"
#include "LevelLimiter.h"
#include "DocCommentsRewrite.h"
#include "JsCallable.h"
#include "LangSvcExtensibility.h"
#include "AuthorCompletionKindConverter.h"
#include "MissingValueHandler.h"
#include "Structure.h"
#include "ReferenceSet.h"
