/********************************************************
*                                                       *
*   Copyright (C) Microsoft. All rights reserved.       *
*                                                       *
********************************************************/
import "edgescriptDirect.idl";

typedef enum BuiltInOperation
{
    BuiltInOperation_Unknown = 0,

#define BUILT_IN_OPERATION(o, p, f) o,
#include "BuiltInOperations.h"
#undef BUILT_IN_OPERATION

} BuiltInOperation;

[
    object,
    uuid(EBADE2E2-A8CC-4797-A430-2E863867EFD0),
    local,
    pointer_default(unique)
]
interface IJavascriptDispatchLocalProxy : IUnknown {
};

[
    object,
    uuid(E5B35059-A1BE-4977-9BEE-5C44226340F7),
    helpstring("IJavascriptDispatchRemoteProxy Interface"),
    pointer_default(unique)
]
interface IJavascriptDispatchRemoteProxy : IUnknown {
    HRESULT GetTypeId(
        [out] int * typeId);

    HRESULT HasInstance(
        [in] VARIANT instance,
        [out] BOOL *result,
        [out] EXCEPINFO *pei,
        [in] IServiceProvider *pspCaller);

    HRESULT PrivateInvokeEx(
        [in] DISPID id,
        [in] LCID lcid,
        [in] DWORD dwFlags,
        [in] DISPPARAMS *pdp,
        [out] VARIANT *pvarRes,
        [out] EXCEPINFO *pei,
        [in] IServiceProvider *pspCaller);

    HRESULT InvokeBuiltInOperation(
        [in] BuiltInOperation operation,
        [in] WORD wFlags,
        [in] DISPPARAMS *pdp,
        [out] VARIANT *pvarRes,
        [out] EXCEPINFO *pei,
        [in] IServiceProvider *pspCaller);
};
