#if !defined(RECYCLER_SIZE_NO_SUBFIELD)
#error RECYCLER_SIZE_NO_SUBFIELD is not defined
#endif

#if !defined (RECYCLER_SIZE_SUBFIELD)
#error RECYCLER_SIZE_SUBFIELD is not defined
#endif

RECYCLER_SIZE_NO_SUBFIELD(processAllocaterUsedBytes_start)
RECYCLER_SIZE_NO_SUBFIELD(processAllocaterUsedBytes_end)
RECYCLER_SIZE_NO_SUBFIELD(processCommittedBytes_start)
RECYCLER_SIZE_NO_SUBFIELD(processCommittedBytes_end)

RECYCLER_SIZE_SUBFIELD(threadPageAllocator_start, committedBytes)
RECYCLER_SIZE_SUBFIELD(threadPageAllocator_start, usedBytes)
RECYCLER_SIZE_SUBFIELD(threadPageAllocator_start, reservedBytes)
RECYCLER_SIZE_SUBFIELD(threadPageAllocator_start, numberOfSegments)
RECYCLER_SIZE_SUBFIELD(threadPageAllocator_end, committedBytes)
RECYCLER_SIZE_SUBFIELD(threadPageAllocator_end, usedBytes)
RECYCLER_SIZE_SUBFIELD(threadPageAllocator_end, reservedBytes)
RECYCLER_SIZE_SUBFIELD(threadPageAllocator_end, numberOfSegments)
RECYCLER_SIZE_SUBFIELD(recyclerLeafPageAllocator_start, committedBytes)
RECYCLER_SIZE_SUBFIELD(recyclerLeafPageAllocator_start, usedBytes)
RECYCLER_SIZE_SUBFIELD(recyclerLeafPageAllocator_start, reservedBytes)
RECYCLER_SIZE_SUBFIELD(recyclerLeafPageAllocator_start, numberOfSegments)
RECYCLER_SIZE_SUBFIELD(recyclerLeafPageAllocator_end, committedBytes)
RECYCLER_SIZE_SUBFIELD(recyclerLeafPageAllocator_end, usedBytes)
RECYCLER_SIZE_SUBFIELD(recyclerLeafPageAllocator_end, reservedBytes)
RECYCLER_SIZE_SUBFIELD(recyclerLeafPageAllocator_end, numberOfSegments)
RECYCLER_SIZE_SUBFIELD(recyclerLargeBlockPageAllocator_start, committedBytes)
RECYCLER_SIZE_SUBFIELD(recyclerLargeBlockPageAllocator_start, usedBytes)
RECYCLER_SIZE_SUBFIELD(recyclerLargeBlockPageAllocator_start, reservedBytes)
RECYCLER_SIZE_SUBFIELD(recyclerLargeBlockPageAllocator_start, numberOfSegments)
RECYCLER_SIZE_SUBFIELD(recyclerLargeBlockPageAllocator_end, committedBytes)
RECYCLER_SIZE_SUBFIELD(recyclerLargeBlockPageAllocator_end, usedBytes)
RECYCLER_SIZE_SUBFIELD(recyclerLargeBlockPageAllocator_end, reservedBytes)
RECYCLER_SIZE_SUBFIELD(recyclerLargeBlockPageAllocator_end, numberOfSegments)

#ifdef RECYCLER_WRITE_BARRIER_ALLOC_SEPARATE_PAGE

RECYCLER_SIZE_SUBFIELD(recyclerWithBarrierPageAllocator_start, committedBytes)
RECYCLER_SIZE_SUBFIELD(recyclerWithBarrierPageAllocator_start, usedBytes)
RECYCLER_SIZE_SUBFIELD(recyclerWithBarrierPageAllocator_start, reservedBytes)
RECYCLER_SIZE_SUBFIELD(recyclerWithBarrierPageAllocator_start, numberOfSegments)
RECYCLER_SIZE_SUBFIELD(recyclerWithBarrierPageAllocator_end, committedBytes)
RECYCLER_SIZE_SUBFIELD(recyclerWithBarrierPageAllocator_end, usedBytes)
RECYCLER_SIZE_SUBFIELD(recyclerWithBarrierPageAllocator_end, reservedBytes)
RECYCLER_SIZE_SUBFIELD(recyclerWithBarrierPageAllocator_end, numberOfSegments)

#endif
